apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/generate-same-namespace.yaml
patches:
  - path: allow-gateway-frontend-patch.yaml
    target:
      kind: CiliumClusterwideNetworkPolicy
      name: allow-gateway-frontend
  - path: allow-kube-system-patch.yaml
    target:
      kind: CiliumClusterwideNetworkPolicy
      name: allow-kube-system
