minio:
  image:
    tag: RELEASE.2025-07-18T21-56-31Z-cpuv1

  mcImage:
    tag: RELEASE.2025-07-18T21-56-31Z-cpuv1

  replicas: 3

  persistence:
    size: 50Gi

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    tls:
      - hosts:
          - minio.yuriy-lab.cloud
        secretName: minio-ingress-tls
    hosts:
      - minio.yuriy-lab.cloud
    path: "/"

  consoleIngress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    tls:
      - hosts:
          - minio-console.yuriy-lab.cloud
        secretName: minio-console-ingress-tls
    hosts:
      - minio-console.yuriy-lab.cloud
    path: "/"

    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 1Gi
        cpu: 200m

    metrics:
      serviceMonitor:
        enabled: true
        namespace: monitoring