yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "minio.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: minio-console
      port: 9001

  ciliumNetworkPolicies:
    - policyName: minio-ingress-policies
      type: namespaced
      endpointSelector:
        matchLabels:
          app: minio
      ingress:
        - fromEndpoints:
            - matchLabels:
                gateway.envoyproxy.io/owning-gateway-name: main-gateway
                gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
                io.kubernetes.pod.namespace: envoy-gateway-system
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9001"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/name: loki
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: mimir
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: compactor
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: compactor
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: ingester
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: querier
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: ingester
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: querier
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: query-scheduler
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: store-gateway
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/component: index-gateway
                io.kubernetes.pod.namespace: loki
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"
                  protocol: TCP
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
                app.kubernetes.io/name: alloy-metrics
                io.kubernetes.pod.namespace: k8s-monitoring
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "9000"



minio:
  image:
    tag: RELEASE.2025-04-22T22-12-26Z-cpuv1

  mcImage:
    tag: RELEASE.2025-04-16T18-13-26Z-cpuv1


  existingSecret: minio-credentials

  replicas: 1
  mode: "standalone"


  persistence:
    size: 50Gi
    storageClass: "truenas-iscsi"

  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 1Gi
      cpu: 200m

  metrics:
    serviceMonitor:
      enabled: true
      includeNode: true

  buckets:
    - name: mimir-data
      policy: none
      purge: false
      versioning: false
    - name: loki-chunks
      policy: none
      purge: false
      versioning: false

    #   # Name of the bucket
    # - name: bucket1
    #   # Policy to be set on the
    #   # bucket [none|download|upload|public]
    #   policy: none
    #   # Purge if bucket exists already
    #   purge: false
    #   # set versioning for
    #   # bucket [true|false]
    #   versioning: false # remove this key if you do not want versioning feature
    #   # set objectlocking for
    #   # bucket [true|false] NOTE: versioning is enabled by default if you use locking
    #   objectlocking: false
    # - name: bucket2
    #   policy: none
    #   purge: false
    #   versioning: true
    #   # set objectlocking for
  #   # bucket [true|false] NOTE: versioning is enabled by default if you use locking
  #   objectlocking: false
