apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: default             # Argo CD project; "default" if you're not using custom projects
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/yuriy/Homelab
    targetRevision: HEAD
    path: kubernetes/apps/cert-manager/manifest
    helm:
      releaseName: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true