apiVersion: v2
name: cloudnative-pg-yk
description: Umbrella Helm chart for cloudnative-pg application in Kubernetes

type: application
version: 0.26.1
appVersion: "0.26.1"

dependencies:
  - name: cloudnative-pg
    version: "0.26.1"
    repository: "https://cloudnative-pg.github.io/charts"
