groups_header_name: "X-Auth-Request-Groups"
user_header_name: "X-Auth-Request-Email"

apps:
  whoami:
    allowed_groups:
      - "admins"
      - "whoami-users"
  grafana:
    allowed_groups:
      - "admins"
      - "monitoring-team"
  prometheus:
    allowed_groups:
      - "admins"
      - "sre-team"