yk:
  gateways:
    - name: main
      hostname: "fdved.cei"
      replicas: 3
      envoyProxy:
        service:
          type: LoadBalancer
          loadBalancerIP: 10.0.8.105
        deployment:
          envoy:
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                cpu: 100m
                memory: 512Mi
      listeners:
        - name: https
          protocol: HTTPS
          port: 443
          hostname: "*.yuriy-lab.cloud"
          allowedRoutes:
            namespaces:
              from: All
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                group: ""
                name: main-gw-tls-cert



gateway-helm:

  deployment:
    replicas: 3

  pod:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            "app.kubernetes.io/instance": envoy-gateway
            "app.kubernetes.io/name": gateway-helm

  podDisruptionBudget:
    minAvailable: 1

  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
