- Core:
    - Git Homelab:
        icon: github.svg
        href: https://github.com/yuriy-kovalchuk/Homelab
        description: YK Homelab
    - ArgoCD:
        icon: argo-cd.svg
        href: https://argocd.yuriy-lab.cloud
        description: YK ArgoCD instance
    - Proxmox:
        icon: proxmox.svg
        href: "https://firewall.yuriy-lab.cloud:8006"
        description: firewall
    - Authentik:
        icon: authentik.svg
        href: "http://authentik.yuriy-lab.cloud/"
        description: YK IDP
    - Longhorn:
        icon: longhorn.svg
        href: "http://longhorn.yuriy-lab.cloud/"
        description: k8s storage
    - Vault:
        icon: vault.svg
        href: "http://vault.yuriy-lab.cloud/"
        description: Vault PRD
    - Netbox:
        icon: netbox.svg
        href: "http://netbox.yuriy-lab.cloud/"
        description: Netbox PRD
- Monitoring:
    - Grafana:
        icon: grafana.svg
        href: "https://grafana.yuriy-lab.cloud"
        description: YK Grafana
    - Prometheus:
        icon: prometheus.svg
        href: "https://prometheus.yuriy-lab.cloud"
        description: YK Prometheus
    - Kyverno:
        icon: "https://repository-images.githubusercontent.com/169108858/35923880-823a-11e9-9089-0c9c102f9e6f"
        href: "https://kyverno-reporter.yuriy-lab.cloud"
        description: YK Kyverno Reporter
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "https://kuma.yuriy-lab.cloud"
        description: internal
    - Alert Manager:
        icon: alertmanager.svg
        href: "https://alertmanager.yuriy-lab.cloud"
        description: YK Alert Manager
#    - Kiali:
#        icon: "https://avatars.githubusercontent.com/u/36001875?v=4"
#        href: "https://kiali.istio.yuriy-lab.cloud"
#        description: YK Kiali
- Containers:
    - Headlamp:
        icon: headlamp.svg
        href: "https://headlamp.yuriy-lab.cloud"
        description: Headlamp K8S
    - Portainer:
        icon: portainer.svg
        href: "https://portainer.yuriy-lab.cloud"
        description: docker
    - Harbor:
        icon: harbor.svg
        href: "https://harbor.yuriy-lab.cloud"
        description: YK Container Registry
- Storage:
    - Minio K8s:
        icon: minio.svg
        href: "https://minio.yuriy-lab.cloud"
        description: YK Minio K8s
    - Minio Proxmox:
        icon: minio.svg
        href: "http://10.0.10.10:9001"
        description: YK Minio Proxmox
- Network:
    - OpnSense:
        icon: opnsense.svg
        href: "https://opnsense.yuriy-lab.cloud"
        description: OpnSense
    - Nginx:
        icon: nginx.svg
        href: "http://10.0.10.5:81"
        description: Nginx Proxy Manager
