- Core:
    - ArgoCD:
        icon: argo-cd.svg
        href: https://argocd.yuriy-lab.cloud
        description: YK ArgoCD instance
    - Proxmox:
        icon: proxmox.svg
        href: "https://10.0.1.1:8006"
        description: firewall
    - Longhorn:
        icon: longhorn.svg
        href: "http://longhorn.yuriy-lab.cloud/"
        description: k8s storage
    - Vault:
        icon: vault.svg
        href: "http://vault.yuriy-lab.cloud/"
        description: Vault PRD
- Monitoring:
    - Grafana:
        icon: grafana.svg
        href: "https://grafana.yuriy-lab.cloud"
        description: YK Grafana
    - Prometheus:
        icon: prometheus.svg
        href: "https://prometheus.yuriy-lab.cloud"
        description: YK Prometheus
    - Kyverno:
        icon: kyverno.svg
        href: "https://kyverno-reporter.yuriy-lab.cloud"
        description: YK Kyverno Reporter
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "https://kuma.yuriy-lab.cloud"
        description: internal
    - Alert Manager:
        icon: alertmanager.svg
        href: "https://alertmanager.yuriy-lab.cloud"
        description: YK Alert Manager
- Containers:
    - Rancher:
        icon: rancher.svg
        href: "https://rancher.yuriy-lab.cloud"
        description: rancher k8s
    - Portainer:
        icon: portainer.svg
        href: "https://portainer.yuriy-lab.cloud"
        description: docker
    - Harbor:
        icon: harbor.svg
        href: "https://harbor.yuriy-lab.cloud"
        description: YK Container Registry
- Storage:
    - Minio K8s:
        icon: minio.svg
        href: "https://minio-console.yuriy-lab.cloud"
        description: YK Minio K8s
    - Minio Proxmox:
        icon: minio.svg
        href: "http://10.0.10.10:9001"
        description: YK Minio Proxmox
- Network:
    - OpnSense:
        icon: opnsense.svg
        href: "https://10.0.1.254"
        description: OpnSense
    - Nginx:
        icon: nginx.svg
        href: "http://10.0.10.5:81"
        description: Nginx Proxy Manager
