apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argo-cd
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    path: kubernetes/apps/uptime-kuma/manifest
    targetRevision: HEAD
    helm:
      releaseName: uptime-kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        # This will enable Goldilocks/VPA for the entire namespace
        goldilocks.fairwinds.com/enabled: "true"
