apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yk-talos-manager
  namespace: yk-talos-manager
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: yk-talos-manager
    namespace: yk-talos-manager
  install:
    createNamespace: false
  values:
    replicaCount: 1

    serviceAccount:
      create: true
      annotations: {}

    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

    ports:
      metrics: 8080
      health: 8081
      webhook: 9443

    metrics:
      enabled: false
      service:
        type: ClusterIP
        port: 8080

    leaderElection:
      enabled: true
      id: yk-talos-management.lock

    webhooks:
      enabled: false
      certManager:
        enabled: true
        issuerRef:
          name: selfsigned-issuer
          kind: ClusterIssuer

    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

    securityContext:
      runAsUser: 65532
      runAsGroup: 65532
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    crds:
      install: true

    nodeSelector: {}
    tolerations: []
    affinity: {}
