apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: yk-talos-manager
  namespace: yk-talos-manager
spec:
  interval: 1h
  url: oci://ghcr.io/yuriy-kovalchuk/charts/yk-talos-management
  ref:
    tag: "0.4.0-alpha"
