{{- range .Values.yk.gateways }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .name }}-proxy
  namespace: {{ $.Release.Namespace | default "envoy-gateway-system" }}
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyPDB:
        minAvailable: 1
      envoyDeployment:
        replicas: {{ .replicas }}
        container:
          resources:
            requests:
              cpu: {{ .envoyProxy.deployment.envoy.resources.requests.cpu }}
              memory: {{ .envoyProxy.deployment.envoy.resources.requests.memory }}
            limits:
              cpu: {{ .envoyProxy.deployment.envoy.resources.limits.cpu }}
              memory: {{ .envoyProxy.deployment.envoy.resources.limits.memory }}
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  "gateway.envoyproxy.io/owning-gateway-name": "main-gateway"
      envoyService:
        type: {{ .envoyProxy.service.type }}
        loadBalancerIP: {{ .envoyProxy.service.loadBalancerIP }}
---
{{- end }}