apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  gatewayClassName: envoy-gw
  listeners:
    - name: https-multiple-listeners
      protocol: HTTPS
      port: 443
      hostname: "internal.yuriy-lab.cloud"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ''
            name: internal-tls-cert
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.yuriy-lab.cloud"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ''
            name: main-gw-tls-cert