yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: alloy
      hostnames:
        - "alloy.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: alloy
        port: 12345

alloy:
  alloy:
    enableReporting: false
    configMap:
      content: |
        // Define the destination for scraped metrics: your Mimir distributor endpoint.
        // No headers are required in this configuration.
        prometheus.remote_write "mimir_remote_write" {
        // Replace with the actual URL of your Mimir Distributor service
          endpoint {
            url = "http://mimir-distributor.mimir.svc.cluster.local:8080/api/v1/push"
          }
        
          remote_timeout = "30s"
        }


#  serviceMonitor:
#    enabled: false