apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: immich-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: immich
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: immich/db
        property: password
