apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-config
  namespace: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          log:
            level: info
            job_level: info

          runner:
            capacity: 1
            timeout: 3h
            fetch_interval: 2s
            labels:
              - "docker:docker://docker.io/catthehacker/ubuntu:act-24.04"

          cache:
            enabled: true

          container:
            privileged: false
            docker_host: unix:///var/run/docker-sock/docker.sock

          server:
            connections:
              workload-prd:
                url: http://forgejo-http.forgejo.svc.cluster.local:3000/
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
  data:
    - secretKey: uuid
      remoteRef:
        key: forgejo/runner
        property: uuid
    - secretKey: token
      remoteRef:
        key: forgejo/runner
        property: token
