apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud-admin
  namespace: opencloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: opencloud-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: opencloud/admin
        property: password
