apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-secret-store.yaml
  - apps-forgejo.yaml
  - apps-immich.yaml
  - apps-opencloud.yaml
  - core-cert-manager.yaml
  - observability-alertmanager.yaml
  - observability-grafana.yaml
  - observability-loki.yaml
  - observability-mimir.yaml
  - observability-tempo.yaml
  - platform-cloudflared.yaml
  - platform-democratic-csi-iscsi.yaml
  - platform-democratic-csi-nfs.yaml
  - platform-yk-dns-manager.yaml
  - vms-ubuntu-test.yaml
