apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: basic-auth
  data:
    - secretKey: auth
      remoteRef:
        key: prd/longhorn
        property: basic-auth

