---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgCVzrOpQkOLatZFv52Tp4ROlGGy4OrjORZDzybrkkpnhcVHeisJ9jPtlDOiTl2IE7JoP58f7kPTLgJlfqD+CuQCY5e7GRlUhptgBMac8nI5cb0m7iEqh3QEzCCnDQewrAKSbY6XotziVpgI2tYYTTeFTvbqhhovReotPU6o6MF3UzBQxlWQoXYTnnikq2bbFZGgnSYcJy/WL71lU0yhbWlpB6yt796GprnXOWKnvBYYQgwaeqY4mAeWqIva9AL0XGQwvunYkskMNX4Ms3rAJEeD8cCHC59KSIqOdu/1J3oU2XDreY6jAgr08iiRGLjdFIcN2eJV2F4TFSUd3W72Z16ttDW+gxd1FrEqGbw1SIeKa0GITgTSJrYzA5NwJScAvlwJCNMZTJ2BEzyFeEmHs5YpLRJjhXJOVPPdNe7a2n76vxHpxQwWWNes868D/Mp/6Sa29LpDW+iJ4BrhoI/5ETg0ezvXx3X8y2P6mfWndj0k8IeK3JbF0SaFPbD3zUnFw/g8xGFNZmN9roBN0RTzQNa1noqCFeTMb3D3Bt7sny8ojYdzHuUTSZlWFLFVGyZJO2lCiqJHbAQ8nqwyZB0tXso4uyJQFTF4wWqhoGBsoz+ou92cr0uo79gAGQ1rkLMRnAflEJqY3MBq6LDxjDvCQPBvKYl2R80jR4A6NwWFsUORD5O1S7UkEL+lSe+UsJH9YoxHmE/AMvLh
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
