---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgAHrz3XR1opYD5010Cn5oJyRG4CnmpI/ckuyajlueB/d1UQNap98xzTsOF5Q7aQsAFUmWS+pGcLeaz06pVUOIxwx6B3Bfw+f/UFbkzh9Q8So4HwYgsdSJOQ9vLboZK/5eigflDDJODp0pVsCLyxLyhcd8uKP9NPldwk1CKKpzFOvx1a1EwGfEwBjs+goOJ/KbP0A+CnF/EPNBK4imt1zQzXWREg2KbQ+C8h9aLM/5b/To+Sad9U1fo2gb9sk3NsW7IC6ol59OXX0n4Ne2A4ZZyCeXVc8p9XIDG6KuAnNJiNATf0Ma1aXwfz6axtTy6jUa4Tu5qUaMrQBhKR82s5gCf6lOozXhxel9ZX8swKueDyxdt4zCjfD4QQJRL5aerNG21jsY1yfPP9fM3q7Kq0rtHH1rJWZ8mzeHgFh8+fQSGWM3ciOH/1br/0xMGJu3HwDwTma3412NMwN/bUP8pysMEsacEeoLgIER8Dizb/dZahVO+CpVQQjGlwypF1obXeRF7yQ0N6mGZlxnu2arfILg1qbUGoG1TTkQgLRT3xaBjKNyHnV3Rh0RgNWJOmJz1LaqVu/FOiy5k8F+wBhN2MtyJt0P0jJ6FVZnbuP4CZ88yrHdFtm80cmwA1Ad//E9XqMv6YqTUym/qMfwiSr0CzLeBF+MQdHM//YQ3FXRYkMdd1euhWbfNwaB6OK4Dr+HsfRB45yIRmVYZr
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
