---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgA+u+jjadB6dFHrK9D4T8ubDqxspiBeESfbR8k/A4YFhHpYa4n2jP4WLvc02O4QkF8R2iryhQUpUQs4TNTC5CIhL+VegEtjQ/Za+eIeZmFSZ0RNsNe2qGsyuyS9rSnxFfb6GaI58vtBK2rRORN+8IGQl+ybDRVRXcdsxhwEowu396eW9HKxEXrP0lR2F7Z6/lHW/t+T+fKJJp8XWAk1YT6/JVnn9ZAIP5ux5bo6iDTkfUWC0v+ldazJuhE124ZqAkaH1eUDT8q6SlrmRfRLiCocusBel5/v4S/RiTPGAGOHDh+6BnDXZHEEeaccgQQK6lEV60USciIzYfCefyDsWeQJhC0uOEFIArvAhHtVwhkdJ0BqwBnEWbOzONQcv3Hoxe+QID3u0TTWaXQjcYRf/9n0rP48SaNosWwdo0vBzHTapoyaivlG8nBFHLH5tPBaWgMSl/5CYYePBYD+t+oGJu7rwmAx9QBIc0cwmHJ71boKWPEZu0nW/ofef7zyK6/Jtkwd17HI2tAGHYJ5MllZaAtkgKB+vUfwiH3jYf02LwCrEpTa4/+4VkqjDJi/+M4GJY+bHmvjZl5Wzp2x2Gs20D8smb8GfN8jamUNRzfZ2wM546EKVJbIgRFlzPi1ySjT95khyXdMfj37k5a1AIonycsgjWr7OmjmvTqntaoFkbgIO3vYDsOzu/5AK/64iqU6P+2itNA16bIOq9VyER8JnaIQzXtMs/ZjKsA4I9nAMZuiY0rFsumyQue2HjuO
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: longhorn-system
