apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - node-not-ready.yaml
  - node-resources.yaml
  - workload-health.yaml
  - storage.yaml
  - certificates.yaml
  - database.yaml
  - gitops.yaml
  - capacity.yaml
  - cluster-core.yaml
  - secrets.yaml
  - admission-control.yaml
