apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret.yaml
  - pvc.yaml
  - cnpg-cluster.yaml
  - valkey.yaml
  - server.yaml
  - machine-learning.yaml
  - network-policy.yaml
  - policy-exception.yaml
