apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: immich-gpu
  namespace: immich
spec:
  matchConditions:
    - name: exclude-immich-gpu
      expression: >-
        object.metadata.namespace == 'immich' &&
        'app' in object.metadata.labels &&
        object.metadata.labels['app'] in ['immich-server', 'immich-machine-learning']
  policyRefs:
    - kind: ValidatingPolicy
      name: disallow-host-path
    - kind: ValidatingPolicy
      name: disallow-privilege-escalation
    - kind: ValidatingPolicy
      name: disallow-privileged-containers
    - kind: ValidatingPolicy
      name: require-run-as-non-root-user
    - kind: ValidatingPolicy
      name: require-run-as-nonroot
    - kind: ValidatingPolicy
      name: restrict-seccomp-strict
    - kind: ValidatingPolicy
      name: restrict-volume-types
