apiVersion: talos.yuriykovalchuk.dev/v1alpha1
kind: TalosCluster
metadata:
  name: management-prd
  namespace: default
spec:
  clusterName: managment-prd
  endpoints:
    - 10.0.2.2
  talosVersion: v1.13
