apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opnsense-credentials
  namespace: ingress-watcher
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: opnsense-credentials
  data:
    - secretKey: OPNSENSE_SECRET
      remoteRef:
        key: prd/ingress
        property: OPNSENSE_SECRET
    - secretKey: OPNSENSE_KEY
      remoteRef:
        key: prd/ingress
        property: OPNSENSE_KEY

