---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opnsense-credentials
  namespace: ingress-watcher
spec:
  encryptedData:
    OPNSENSE_SECRET: AgBn8hWqJ9lUHxBxTLMTiDOlQUavw+IYBUAddVxdkSc8Vnt1hy57pS/tX9Fl+Ee01ITkqNXWhM+VKSglKl8ApBaFC8Siy7D0kSIJGSZVO4RKJBL+LWxf1ytrwKKebaqY4KYyZuPHgHdmND9KuiSJ5BHmedi00986SufdgWss4iT2gAHy5tfv4fBZ+wefDRDMcDrxYVeErCdvJPJYSCPfOuOxB9tNdD9ecX0o8fNngFHyE/bdjsgSQZC30PYB2iG7yUF8Eusv6cvGyvYhXXkAZac5RaBzmMhqMFhdccS5HFusbd6XHsntYwddzWMGG3xnMbtz5KAXSRskSMc3F2FzWVFnC7EJcdOKmJ5NTdaXqKyxK9ybm9tEYl83dxawj7oBHFQOgAIpUS6Cxr3ULOFjMOkzyDeQXFxpl4eqSN482yps4gznOWnanWJh2GttXmWBuV/srzRLm4jJL/oR+NiZYbvHzeIDiYd1lUEYHlED6ZGxYRalueaYNtoUUIkqxC9ytxuxExC9JloShNvcY8kK9Vaty7qsKZ6zspOYxPgXD89mH/BZMOmxQB66h1XLE7e30oPHSoh8ihFOBeLT9SYUhfwhHJJDPSdSdSbkbSSd6Dgqn5/CiqLgX5PMcbFoTZ61pQyv7hD5cFy7VqIpoICjzb57R2o7ZDSfpyQiHXUHiQ1FsKyF0wrj0p7Xxn5vJrPrWplzmHZhCSmfp68IZthzgJj2Q0HwzhEYUrIV7UdcQyYjDryj3J4Z6lhN6iRDurstlfSrpSupWm3DhV/lOU6lctBCVlX2l5McuHvV2zdjXhYnBg==
    OPNSENSE_KEY: AgCYJ7YjaYJSSIJZVCUKfcSypCW3JYTEHAuogTYtrEP7tob8D5eTqnlTJxjDwI4gKAY3UdU7s99B0ltLlNbjuIoaw6Mq72DFfnD50jUd9g5yzXWeMGB6HVyQvNSdw9Ser7OuxUbTfosjxDfA2nuX1NjqLdNBzuRiwK3ELhqgzRnJ9QuZO6hOxn//kzCCgCYGIRK7jE/T/pv/NdhCkkoJzhCu3Kzolzy6HpoNYOm2yuFO2FeJW7xmDkbGhvPRywqa4PzAfSJ/FuD/KDw+N0NnUCfbzkYXJ1xUXYl6qkOu2pGzPzlEG3SS7uCwxIjb3Eh/iRyZzOwwKl2PBY4ON/UMp25JHmyT62HrIkNT4dT2I/q+g/WypPkU4zO5+GD+EgISi1B5OzlSwTL4fkFgA71oPTXoR74H8MHefsFWCVWRiiOVSYNBNnhMzIMVT57h559HGR6uT0LpWNAsKoM0ANqo85ju+mwkL/DBP9V7780DIhzDvIgH/xh+UXKSm31tcbCBfuOU1JBZ+kDlhiaJko9+9xqyk1MTIUGcaFlLb5dCI4uoCiBkgUjVpfiXp3m4ZZna5odAaHtaJxwskPldBQN0RpovFOAFNnttcM8n/97hhjriNkwD7nMC/UFj1opTaJCgDd+YmvD7ZeJr2wwnH/bnzDHfSD2sMjaXlLvCud4myfa90mcGpbnP4qw5EoSovUkepOJgsiPFcI0syG30WOptpAktF5y9D9uaj4UvgMbECkBzMCahaeGPI6IUaKGyNXD84NUpsRDOnG23kWkhAdr5eA8jAZDndxWOeoMpCXsJNJDiEA==
  template:
    metadata:
      creationTimestamp: null
      name: opnsense-credentials
      namespace: ingress-watcher
