---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opnsense-credentials
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    OPNSENSE_KEY: AgAESNPPE4nPC8jwG/nmI+ziWs4j8q+E/NbvxAR9oDePiLajTo6lKezyo162NEboM8UXjmeybaxAff09sVrHL/v69IVzinRpCcmmITxGceAXznkzgK013F20Xybhxfw8OFyWsjdYnhGTafAPYwjPrH9gLOPGN0gYAMv0AYh7HtXaEqqGsEuMr886VVLI54BtpkfUOENbSUvfEQG2G5UdMcUJ90gxVZQ4uuMVwG/4FbOh3C6HtDtCXGK3LeqjbRXtSH4haEyma4NstB6A7EdsV/UzqlSBTDodyCe7AqNBbonENTVLh7FcvOANdOoqfkfdU/elLOunYqKRhNXqGF02OXudXxg3lGgXAfCY3FfkufKD4SkNvVejFTlJY+KG7yZFpWie/LEwt00+/H0xOKUfWtby+AczMNX8Kg61NWCsjvf1/8+KCSVA89FawbeKTkWMUMU/NpFzSiehjIPW7Xt2Cei0g2D+qZGL8nnaQGUooDfraIPg8ULdUAEV1DnI0LnBQ8vOZFfa8VyyoeqO0eWHbOJDdLEM0Li2ZHDEfMyFUJAq1hPjjAAwtcJml+hKi0Sj666PNDb1It4LWmritwGc4cZNei6uxAZAi3vVDVN1Sg59RXB3oMAYE4XYalXTmrvsVtVHyxZVSkLlw7CNSZ77KCg9+PTCdqvB7EQ4tHZZrXc05scQO18v/We6uIgMN3FbKMy5Qd25WOoNK1dZ0MZL+FFdDOEXBdH0grYlDMbg+V5l3LP9Wk7KyGo73lBvuzfmrHx2RausBNLXLrWKdhltV2yDVDKNuYF/j5uuUONvu7ZwoA==
    OPNSENSE_SECRET: AgAF+fDBjcxj+B66FuGuhqIIsE8s8rg5AndXDYrtDNt951n6kKf1Xfk26m3j0MgvxU7oriPpyzCioQHp7sMo4VYvJPq+WGNFAJphpXBl14LpV3syvjPhSOL/vQjhGwK8XhMT95qAlXIRp+LHtAFt5GKYdoEF75korMUE3t7Hv1DBY9trVxr3YBYoEWpS8K0/RAGcWru60wa0GKt3YdoJQxOyBSwfSX0JJpppUm9/PVYdNHHzjHFTuvIanBplV9ECKuHoMNoAPzvI+yUXQqnrk+rzbqf8+H7K28V03drVIQfY9vlnIgW7X2zE0rqI9qgNI4Vk7enShGk11zAK7U0VzWywkexhq+3xAO9UcjCkiGRHEjgbXBjj+Ss7LgisvmQr0cGKnYF6+MySClgOj/yWLbuSU+hHppgJtzdiN3ALSdJ9hwc9Iy4t2+NwP911t9sGO1z+7g3d3UWdI+hkPAJdN4h6P4bJZ2+Lba9L5kIx6HJjuHKPjtRHvUKDw9udVYi5yYQpQGRy1qUm+ZAvEzs9AcprINO4XJ0w4zZG8LNbnTlvfvXF94ZfbMic9AOtVcfmBDQyUqTJZ4HbBy/rl1TTkogyV5R3eAAicZnDeyxF8VPYJKAuw16/PsnWqaH0IZiNYJROqoKLjYFkMH9++7bct2IrjXmPNgVDsySKPlmIbt6XfJkFN09hYLABrOt+VDKka0kTYrAJdCp6u+fu0BVBHLQXB7/ZDfSjvDBhZJkaXjXWPLemQFl9jkvxYu0I0uRXTVbjRwTXhA0ifw80fCaygTYEK0oHG1rWN7odfq0QXJvaQg==
  template:
    metadata:
      creationTimestamp: null
      name: opnsense-credentials
      namespace: {{ .Values.namespace }}
