---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opnsense-credentials
  namespace: ingress-exporter
spec:
  encryptedData:
    OPNSENSE_KEY: AgBUPl8dVQQ3ixOQr3D0qapXEpSEbIzsdZASm/KSPF+LdgCKdA4HJBL8audJfYpcHPMzebHZuLPVxeoohoQ22DL0soxcXmPGHgN6Z+6PvFGLG47RkQLbNzdkhidByaO+iSjPnfE00WoJgAoWxlVogsSn0fz4HlA/S8lihWr+L88VakEWghkRWB6Nye2hKNdt1bYSYoexnTNoT6/lK4l1YDVhm/4Rv1sLmkI9Va6lgZsZG35eQlNm80NarYr9tRhU/tuQmb0frwW//CI41J8LdCpFA/FzrS+FByLX3JTWF6OGZEa1a0tq15ulOKPNzyEWk28eH9fUDv7S+CHBggkYuNoUD77kSv/F0iAdBrUVi7qkjxD38nU5rUlvjlTC4S75kW8FGAo1b8STZvG6IwfQTkc350UzcN4jb4qNP50uVz88um21htr1JPOUm1jSUrM7OSXDLJ5cKhUb/0Th4J6maW0LiMR/gemOXjp9WA+UewW4Pp0/k0zDRCqc/Zaeijah1lyxuvaAlh/5XcIs/d1ZBzTmwVNjixDAri4Bt44UM5H8MHmw5owXhZIZJVY05TsmeNxX+uZiTsY0p2t3nPDFhhklNY78hKDdYVcLeol3gFAM5OphdNk79icsmLa08hOUgkKjwl0C9DGqzJgRPLVX7SG5Vs/oO0QS8k8p9eoxESu6qxnhxkwXA2V2JOlR/VyCFMv/STPjNsbJMol9jl6FkW5HQfuaB/eIRwtK0cEOB6Y4wkPdrAILlwqdn+PpOg7ogE8MQJkbfQqrxVe3SbZHaLtIgWI5SiixvIRWwub9Bn+fFw==
    OPNSENSE_SECRET: AgCaUG4fDGJZ6d6t4v7ov9Hw6RG2jUCthptbJ4LztX+uZanDuSLBXhE2BqN6IZl1aGDO2mkiEg4lIOAITsxdL8PdErELmjBbH20yT8obMWxuWeKei3UBNQFn/W5VYar7X06hz9TbA5knSoASSAO8jdkVanveHHxVZd4Bbe+Iup/dBy6SyxmGRJDu7VuB0ffy0vSPahk3jq8XEPJNognEiIeC6jnCF5gXly1qZPJcR3pxfZUREh2Gh6r1reAMaWeYIS9jIHwrr0l3rWzccVPqPcxpl4zU5S/0x1/CTMj4g6hAUpBMt4DxG+RRR/4J77p+I44ByA7956fbdfHnPeQPS0hPF4JLkdzgC8+Iue1BmISdphwlDeQ+R+dWOa2FwLwAhBsMZ/H/QxAG1drEzsJKOcLqSZYofPmHBSj9t+y2YMLyWJcb4NaI/XY+yNwnA4BK4zcLxJ9YTyufp/5Cyud3fhcu/IaTFVDbdG1cmlRMMgfNCGiBtiTJmhr+3ai1hjartVp6X6iMnpFok3CZfPsv1Yw9eD0iRjksrzwgtT6Wq7Rc17Iy58tvSu7fqPx44/e3chFc/+6ybMFgaMmZqcWXKEBIK7QzEfufDefbEoWyWjsfndCuqEcJB1brP8Vftusi1Olbp5YNp6f1u4e5R81YlXcAHKN2gC8lePdi9DqF5ZQD0wjV5R/0WwoTVdRr8UhBRfoYXTgtKV90PM51AbIAshO/ncsRjIWKs6RbgSlKjBobqPGEuhCVe16huKcndKvN2gglWBVObI/EMojoWQfMkKSmiDZ5nmqKCLSIEACqsYG7Uw==
  template:
    metadata:
      creationTimestamp: null
      name: opnsense-credentials
      namespace: {{ .Values.namespace }}
