apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gateway-api-crds/overlays/management-prd
  - ../../cert-manager/overlays/management-prd
  - ../../kyverno/overlays/management-prd
  - ../../cilium-policies/overlays/management-prd
