apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-ingester-to-access-minio"
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow Ingester to access Minio"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/instance: loki
  egress:
    - toEndpoints:
        - matchLabels:
            app: minio
            io.kubernetes.pod.namespace: minio
      authentication:
        mode: "required"