apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-alloy-logs"
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow Alloy logs"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
      app.kubernetes.io/instance: loki
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: k8s-monitoring-alloy-logs
            app.kubernetes.io/name: alloy-logs
            io.kubernetes.pod.namespace: k8s-monitoring
      authentication:
        mode: "required"