---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 2m
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./kubernetes/core/overlays/workload-prd
  prune: false
  wait: true
  timeout: 10m
