apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-sync.yaml
  - namespaces.yaml
  - network-policies.yaml
  - core.yaml
  - policies.yaml
  - secrets.yaml
  - platform-infra.yaml
  - platform-ops.yaml
  - observability.yaml
  - alerting-rules.yaml
  - apps.yaml
  - vms.yaml
