---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: llm
  namespace: flux-system
spec:
  interval: 2m
  dependsOn:
    - name: platform
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./kubernetes/llm/overlays/workload-prd
  prune: true
  wait: false
