---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vm-ubuntu-test
  namespace: flux-system
spec:
  interval: 2m
  dependsOn:
    - name: platform-infra
  sourceRef:
    kind: GitRepository
    name: homelab
  path: ./kubernetes/vms/ubuntu-test
  prune: true
  wait: false
  timeout: 5m
