apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argo-cd
spec:
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/template/metadata/annotations
        - /spec/updateStrategy/rollingUpdate/partition
        - /status
        - /metadata/creationTimestamp
        - /spec/volumeClaimTemplates
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/mimir/manifest
    helm:
      releaseName: mimir
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true


