apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-netbox-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: cluster-netbox-user
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/netbox
        property: pg_user
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/netbox
        property: pg_password

