# Disable high availability (HA)
replicaCount: 1


# Set persistence options to use a local volume for SQLite (no external DB needed)
persistence:
  enabled: true
  size: 1Gi

# Disable extra features like Gitea in HA setup
ingress:
  enabled: false


# Optional: Set extra resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

redis-cluster:
  enabled: false

redis:
  enabled: false

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      size: 1Gi