apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi-nfs
spec:
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    storageClasses:
      - name: truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
          - nosuid
          - nodev
          - noexec

    driver:
      existingConfigSecret: truenas-nfs-secret
      config:
        driver: freenas-api-nfs
