apiVersion: v2
name: oauth2-proxy-yk
description: Umbrella Helm chart for oauth2-proxy application in Kubernetes

type: application
version: 1.0.0
appVersion: "8.5.1"

dependencies:
  - name: oauth2-proxy
    version: "9.0.1"
    repository: https://oauth2-proxy.github.io/manifests
