apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-dns.yaml
  - allow-health-probes.yaml
  - allow-kube-system.yaml
  - allow-flux-system.yaml
  - allow-alloy-metrics-scraping.yaml
  - allow-gateway-frontend.yaml
