apiVersion: v1
kind: Secret
metadata:
  name: kiali-dashboard-user-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: kiali-dashboard-user
type: kubernetes.io/service-account-token