{
 "title": "Cilium Operator",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  { "title": "LB IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "IP Addresses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_operator_lbipam_ips_used + cilium_operator_lbipam_ips_available) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "EC2 API Interactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_ec2_api_duration_seconds_sum[1m])/rate(cilium_operator_ec2_api_duration_seconds_count[1m])",
     "legendFormat": "{{operation}} {{response_code}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_services_matching",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "# interfaces with addresses available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_ips_available",
     "legendFormat": "interfaces"
    }
   ]
  },
  {
   "title": "Metadata Resync Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_lbipam_services_unsatisfied[1m])",
     "legendFormat": "operations"
    }
   ]
  },
  {
   "title": "EC2 client side rate limiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_ec2_api_rate_limit_duration_seconds_sum[1m])/rate(cilium_operator_ec2_api_rate_limit_duration_seconds_count[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Interface Creation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(rate(cilium_operator_lbipam_event_processing_time_seconds_count[5m])[1m])) by (subnetId, status)",
     "legendFormat": "{{status}} ({{subnetId}})"
    }
   ]
  }
 ]
}