apiVersion: v2
name: headlamp-yk
description: Umbrella Helm chart for headlamp application in Kubernetes

type: application
version: 0.39.0
appVersion: "0.39.0"

dependencies:
  - name: headlamp
    version: "0.39.0"
    repository: https://kubernetes-sigs.github.io/headlamp/

