headlamp:

  config:
    inCluster: true
    # -- base url path at which headlamp should run
    baseURL: "headlamp.yuriy-lab.cloud"
    oidc:
      clientID: "JW5BvuhoQ8W662jSRMnjjt11lwvhf4tXyoi7JDfa"
      issuerURL: "https://authentik.yuriy-lab.cloud/application/o/headlamp/"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    tls:
      - hosts:
          - headlamp.yuriy-lab.cloud
        secretName: headlamp-ingress-tls
    hosts:
      - host: headlamp.yuriy-lab.cloud
        paths:
          - path: /
            type: ImplementationSpecific
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 512Mi