yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "headlamp.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: headlamp
      port: 80

headlamp:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 512Mi

  extraManifests:
    - |
      apiVersion: v1
      kind: Secret
      metadata:
        name: headlamp-admin-token
        namespace: headlamp
        annotations:
          kubernetes.io/service-account.name: headlamp
      type: kubernetes.io/service-account-token