    apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      name: shared-gateway
      namespace: kube-system
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
    spec:
      gatewayClassName: cilium
      addresses:
        - type: IPAddress
          value: "10.2.0.10"
      listeners:
        - name: http
          port: 80
          protocol: HTTP
          allowedRoutes:
            namespaces:
              from: All
