# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    access_key = "terraform-prd"
    bucket     = "terraform-prd"
    endpoints = {
      s3 = "https://rustfs.yuriykovalchuk.dev"
    }
    insecure                    = true
    key                         = "proxmox-nodes/storage/truenas-setup.tfstate"
    region                      = "eu-south-1"
    secret_key                  = "G7IPKSJ0U5zR7M4Wh7dgOP5RP1fsrPundhY4kinX"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_path_style              = true
  }
}
