yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: alloy
      hostnames:
        - "alloy.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: alloy
        port: 12345

k8s-monitoring:
  cluster:
    name: homelab-cluster

  destinations:
#    - name: loki
#      type: loki
#      url: http://loki-gateway/loki/api/v1/push
    - name: mimir
      type: prometheus
      url: http://mimir-distributor.mimir.svc.cluster.local:8080/api/v1/push

  clusterMetrics:
    enabled: true
    controlPlane:
      enabled: true
    kubeControllerManager:
      enabled: true
    kubeDNS:
      enabled: true
    kubeScheduler:
      enabled: true
    windows-exporter:
      enabled: false
    opencost:
      enabled: false
    kepler:
      enabled: false

  clusterEvents:
    enabled: false
    collector: alloy-logs
    namespaces: []

  nodeLogs:
    enabled: false

  podLogs:
    enabled: false
    gatherMethod: kubernetesApi
    collector: alloy-logs
    labelsToKeep: ["app_kubernetes_io_name","container","instance","job","level","namespace","service_name","service_namespace","deployment_environment","deployment_environment_name"]
    structuredMetadata:
      pod: pod  # Set structured metadata "pod" from label "pod"
    namespaces: []

  alloy-singleton:
    enabled: false

  alloy-metrics:
    enabled: true

  alloy-logs:
    enabled: false
    alloy:
      mounts:
        varlog: false
        dockercontainers: false
      clustering:
        enabled: true

  alloy-profiles:
    enabled: false

  alloy-receiver:
    enabled: false

  extraObjects:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: k8s-monitoring
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
