yk:
  ciliumNetworkPolicies:
    - policyName: allow-egress-to-kube-api-server
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/name: trivy-operator-polr-adapter
      egress:
        - toEntities:
            - kube-apiserver
          toPorts:
            - ports:
                - port: "6443"
                  protocol: TCP

trivy-operator-polr-adapter:

  resources:
     limits:
       cpu: 200m
       memory: 256Mi
     requests:
       cpu: 100m
       memory: 128Mi

  adapters:
    cisKubeBenchReports:
      enabled: false
    complianceReports:
      enabled: true
    rbacAssessmentReports:
      enabled: true
    exposedSecretReports:
      enabled: true
    infraAssessmentReports:
      enabled: true
    clusterInfraAssessmentReports:
      enabled: true
    clusterVulnerabilityReports:
      enabled: true

  podSecurityContext:
    fsGroup: 12345

  securityContext:
    runAsUser: 12345
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault