apiVersion: v2
name: portainer-yk
description: Umbrella Helm chart for portainer on k8s

type: application
version: 2.33.5
appVersion: "2.33.5"

dependencies:
  - name: portainer
    version: "2.33.5"
    repository: https://portainer.github.io/k8s/
