yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "portainer.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: portainer
      port: 9443
      tls:
        enabled: true


portainer:
  service:
    type: ClusterIP

  persistence:
    size: 1Gi
  
  tls:
    force: true

  image:
    tag: lts


  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 512Mi