apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets                # Name of the Argo CD app (visible in Argo CD UI)
  namespace: argo-cd            # Namespace where Argo CD is installed
spec:
  project: default             # Argo CD project; "default" if you're not using custom projects
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/yuriy/Homelab
    targetRevision: HEAD
    path: kubernetes/apps/sealed-secrets/manifest
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc   # Kubernetes cluster to deploy to
    namespace: sealed-secrets                # Namespace where Rancher will be installed
  syncPolicy:
    automated:                         # Enables auto-sync (GitOps!)
      selfHeal: true                   # Auto-correct drift between live & desired state
      prune: true                      # Remove resources that are no longer in Git
    syncOptions:
      - CreateNamespace=true
