yk:
  ciliumNetworkPolicies:
    - policyName: egress-metrics-server-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: metrics-server
      egress:
        - toEntities:
          - host
          - remote-node

metrics-server:

  defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    - --kubelet-insecure-tls

  metrics:
    enabled: true

  serviceMonitor:
    enabled: true

  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 1Gi
