---
- name: System update
  hosts: docker_vm
  become: true
  gather_facts: false

  tasks:
    - name: Wait for cloud-init to finish
      ansible.builtin.command: cloud-init status --wait
      changed_when: false
      failed_when: false

    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        autoremove: true
