apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-1
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.16.1
    helm:
      values: |
        provider:
          name: pihole
        provider: pihole
        policy: upsert-only
        txtOwnerId: "homelab"
        serviceAccount:
          create: true
          name: "external-dns"
        ingressClassFilters:
          - nginx
        extraArgs:
          - --pihole-server=http://10.0.8.154
          - --pihole-password=$(PIHOLE_PASSWORD)
        serviceAccount:
          create: false
        env:
          - name: PIHOLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-dns-password
                key: password
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
