{{- if .Values.yk.httpRoute.backend.tls.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Release.Name }}-backend-tls
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.yk.httpRoute.backend.name }}
  validation:
    wellKnownCACertificates: System  # Or omit validation entirely
    hostname: {{ index .Values.yk.httpRoute.hostnames 0 }}
  {{- end }}