apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generate-same-namespace.yaml
  - mutate-goldilocks-label.yaml
  - mutate-goldilocks-label-rbac.yaml
  - mutate-beyla-instrument-label.yaml
  - cleanup-empty-replicasets.yaml
