apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "longhorn-manager-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: longhorn-manager
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
            app.kubernetes.io/name: alloy-metrics
            io.kubernetes.pod.namespace: k8s-monitoring
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: "9500"
              protocol: TCP
