apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: k8s-monitoring-beyla
  namespace: k8s-monitoring
spec:
  matchConditions:
    - name: exclude-beyla
      expression: >-
        object.metadata.namespace == 'k8s-monitoring' &&
        has(object.metadata.labels) &&
        (
          object.metadata.labels[?'app.kubernetes.io/name'] == 'beyla' ||
          object.metadata.labels[?'app.kubernetes.io/name'] == 'beyla-k8s-cache'
        )
  policyRefs:
    - kind: ValidatingPolicy
      name: disallow-privileged-containers
    - kind: ValidatingPolicy
      name: disallow-host-namespaces
    - kind: ValidatingPolicy
      name: disallow-privilege-escalation
    - kind: ValidatingPolicy
      name: require-run-as-nonroot
    - kind: ValidatingPolicy
      name: require-run-as-non-root-user
    - kind: ValidatingPolicy
      name: restrict-seccomp-strict
    - kind: ValidatingPolicy
      name: restrict-seccomp
    - kind: ValidatingPolicy
      name: disallow-capabilities-strict
    - kind: ValidatingPolicy
      name: disallow-capabilities
