apiVersion: v2
name: httpbin-yk
description: Umbrella Helm chart for httpbin application in Kubernetes

type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: httpbingo
    version: "0.1.1"
    repository: https://estahn.github.io/charts

  - name: oauth2-proxy
    version: "8.3.2"
    repository: https://oauth2-proxy.github.io/manifests
