httpbingo:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
      nginx.ingress.kubernetes.io/auth-url: "http://httpbin-oauth2-proxy.httpbin.svc.cluster.local/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://httpbin.yuriy-lab.cloud/oauth2/start?rd=$escaped_request_uri"
      nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Email, X-Auth-Request-Groups"
      nginx.ingress.kubernetes.io/server-snippet: |
        location /oauth2/ {
          proxy_pass http://httpbin-oauth2-proxy.httpbin.svc.cluster.local;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Scheme $scheme;
          proxy_set_header X-Auth-Request-Redirect $request_uri;
        }
    tls:
      - hosts:
          - httpbin.yuriy-lab.cloud
        secretName: httpbin-ingress-tls
    hosts:
      - host: httpbin.yuriy-lab.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific

