yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "httpbin.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: httpbin-httpbingo
      port: 80

httpbingo:
  replicaCount: 2

  podSecurityContext:
    fsGroup: 2000

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000