apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
  namespace: llm
spec:
  strategy:
    type: Recreate
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-3
      containers:
        - name: llama-cpp
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: dev-dri
              mountPath: /dev/dri
            - name: sys-bus-pci
              mountPath: /sys/bus/pci
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: sys-bus-pci
          hostPath:
            path: /sys/bus/pci
            type: Directory
