yk:

  ciliumNetworkPolicies:
    - policyName: egress-compactor-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: compactor
          app.kubernetes.io/instance: loki
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"

    - policyName: egress-index-gateway-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: index-gateway
          app.kubernetes.io/instance: loki
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"

    - policyName: egress-ingester-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: ingester
          app.kubernetes.io/instance: loki
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"

    - policyName: egress-querier-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: querier
          app.kubernetes.io/instance: loki
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"

    - policyName: egress-distributor-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: distributor
          app.kubernetes.io/instance: loki
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"
    
    - policyName: ingress-from-grafana
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: gateway
          app.kubernetes.io/instance: loki
      ingress:
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/name: grafana
                app.kubernetes.io/instance: grafana
                io.kubernetes.pod.namespace: grafana
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "8080"
                  protocol: "TCP"

    - policyName: ingress-from-logs
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: gateway
          app.kubernetes.io/instance: loki
      ingress:
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/name: alloy-logs
                app.kubernetes.io/instance: k8s-monitoring-alloy-logs
                io.kubernetes.pod.namespace: k8s-monitoring
          authentication:
            mode: "required"


loki:

  global:
    extraArgs:
      - -config.expand-env=true

    extraEnvFrom:
      - secretRef:
          name: loki-s3-secret

  loki:
    auth_enabled: false
    storage:
      type: "s3"
      s3:
        endpoint: http://minio.minio:9000
        region: eu-south-1
        s3ForcePathStyle: true
        accessKeyId: "${S3_ACCESS_KEY}"
        secretAccessKey: "${S3_SECRET_KEY}"
      bucketNames:
        chunks: "loki-chunks"
        ruler: "loki-ruler"
        admin: "loki-admin"

    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
    pattern_ingester:
      enabled: true
    limits_config:
      volume_enabled: true

  deploymentMode: Distributed

  ingester:
    replicas: 2 # To ensure data durability with replication
    zoneAwareReplication:
      enabled: false
  querier:
    replicas: 2 # Improve query performance via parallelism
    maxUnavailable: 1
  queryFrontend:
    replicas: 2
    maxUnavailable: 1
  queryScheduler:
    replicas: 2
  distributor:
    replicas: 2
    maxUnavailable: 1
  compactor:
    replicas: 1
  indexGateway:
    replicas: 2
    maxUnavailable: 1

  bloomPlanner:
    replicas: 0
  bloomBuilder:
    replicas: 0
  bloomGateway:
    replicas: 0

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  singleBinary:
    replicas: 0

  monitoring:
    serviceMonitor:
      enabled: true

    dashboards:
      enabled: true
      namespace: grafana
