yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: outpost
      hostnames:
        - "netbox.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: netbox
        port: 80

netbox:
  superuser:
    name: yuriy
    email: yuriy.kovalchuk@proton.me
#    password: ""
#    apiToken: ""
#    existingSecret: ""

  postgresql:
    enabled: false

  externalDatabase:
    host: pg-cluster-netbox-rw
    port: 5432
    database: netbox
    username: netbox
    existingSecretName: "cluster-netbox-user"
    existingSecretKey: password

  valkey:
    enabled: false