apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../llama-cpp/overlays/workload-prd
  - ../../llama-cpp-cuda/overlays/workload-prd
  - ../../open-webui/overlays/workload-prd
