apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-exporter
  namespace: argo-cd
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    path: kubernetes/apps/ingress-hostname-exporter/manifest
    targetRevision: HEAD
    helm:
      releaseName: ingress-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-watcher
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true