namespace:
  create: true
  name: "dns-sync"

common:
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001


  # Shared Container Security Context applied to ALL containers unless overridden
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false # Highly recommended security setting
    capabilities:
      drop:
        - ALL # Highly recommended security setting

  # Global Topology Spread Constraints (optional)
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: dns-sync


# --- DEPLOYMENTS LIST ---

deployments:
  - name: dns-sync
    enabled: true
    replicas: 3

    envFromConfigMaps:
      - name: opnsense-config-cm
        optional: false

    envFromSecrets:
      - name: opnsense-credentials
        optional: false

    # 1. METADATA CONFIGURATION
    labels:
      service: infrastructure
      env: production
      app.kubernetes.io/name: dns-sync

    # 2. IMAGE CONFIGURATION
    image:
      repository: "harbor.yuriy-lab.cloud/library/opnsense-dns-sync"
      tag: "1.0.0"

    # 3. RESOURCES (If provided, these override the resource defaults)
    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 10m
        memory: 80Mi

    # 5. POD DISRUPTION BUDGET (PDB)
    pdb:
      enabled: true
      # Ensures at least 2 pods are available during voluntary disruptions
      minAvailable: 1

    serviceAccountName: "default"

configMaps:
  - name: opnsense-config-cm
    enabled: true
    data:
      OPNSENSE_URI: "https://opnsense.yuriy-lab.cloud"
      OPNSENSE_KEY: "NuNO/miKt+JhDbdODMWmzEwUohAqjGN67N4dhJh87SgHAMtItQ3emV1vFKx9e+kSAMNmURxnodU4TD5r"
      OPNSENSE_SKIP_TLS_VERIFY: "true"
