apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argo-cd
spec:
  project: default  # Use your desired Argo CD project
  preserveResourcesOnDeletion: true
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  source:
    repoURL: https://portainer.github.io/k8s/  # Helm chart repository URL for Portainer
    targetRevision: "1.0.64"
    chart: portainer  # Helm chart name
    helm:
      releaseName: portainer
  syncPolicy:
    automated:
      prune: true  # Enable pruning of resources when they are removed from the app definition
      selfHeal: true  # Automatically heal the application if there are drifted resources
    syncOptions:
      - CreateNamespace=true
