apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argo-cd
spec:
  project: default  # Use your desired Argo CD project
  destination:
    namespace: portainer
    server: https://kubernetes.default.svc
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/yuriy/Homelab
    targetRevision: HEAD
    path: kubernetes/apps/portainer/manifest
    helm:
      releaseName: portainer
  syncPolicy:
    automated:
      prune: true  # Enable pruning of resources when they are removed from the app definition
      selfHeal: true  # Automatically heal the application if there are drifted resources
    syncOptions:
      - CreateNamespace=true
