yk:
  ciliumNetworkPolicies:
    - policyName: egress-ext-secret-to-vault
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
      egress:
        - toFQDNs:
            - matchName: "*.letsencrypt.org"
          toPorts:
            - ports:
                - port: "443"
                  protocol: "TCP"

    - policyName: allow-egress-to-kube-api-server
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: cert-manager
      egress:
        - toEntities:
            - kube-apiserver
            - remote-node
            - host
          toPorts:
            - ports:
                - port: "6443"
                  protocol: TCP

cert-manager:
  installCRDs: true
  global:
    namespace: cert-manager
  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableGatewayAPI: true

  prometheus:
    servicemonitor:
      # Create a ServiceMonitor to add cert-manager to Prometheus.
      enabled: true
