cert-manager:
  installCRDs: true
  global:
    namespace: cert-manager
  config:
    apiVersion: controller.config.cert-manager.io/v1alpha1
    kind: ControllerConfiguration
    enableGatewayAPI: true

  prometheus:
    servicemonitor:
      # Create a ServiceMonitor to add cert-manager to Prometheus.
      enabled: true
