apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: |
      mode: cluster
    settings.yaml: |
      title: YK Homepage
      background:
        image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
        blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
        saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
        brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
        opacity: 100 # 0-100
      theme: dark
      color: slate
      useEqualHeights: true
      layout:
        Hypervisor:
          header: true
          style: row
          columns: 4
        Containers:
          header: true
          style: row
          columns: 4
        DNS:
          header: true
          style: row
          columns: 4
        Network:
          header: true
          style: row
          columns: 4
        Other:
          header: true
          style: row
          columns: 4
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ""
    services.yaml: |
      - Hypervisor:
          - Proxmox:
              icon: proxmox.svg
              href: "$HOMEPAGE_PROXMOX_NODE1_URL"
              description: node1
              widget:
                  type: proxmox
                  url: "$HOMEPAGE_PROXMOX_NODE1_URL$"
                  username: "{{HOMEPAGE_PROXMOX_NODE1_USER}}"
                  password: "{{HOMEPAGE_PROXMOX_NODE1_PASSWORD}}"
                  node: node1
      - Containers:
          - Longhorn:
              icon: longhorn.svg
              href: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
              description: k8s storage
          - Portainer:
              icon: portainer.svg
              href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
              description: docker
              widget:
                  type: portainer
                  url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
                  env: 2
                  key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
      - DNS:
          - Pi-Hole-0:
              icon: pi-hole.svg
              href: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
              description: quasar
              widget:
                  type: pihole
                  url: "{{HOMEPAGE_VAR_PIHOLE_URL_1}}"
                  key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"
          - Pi-Hole-1:
              icon: pi-hole.svg
              href: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
              description: blazar
              widget:
                  type: pihole
                  url: "{{HOMEPAGE_VAR_PIHOLE_URL_2}}"
                  key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY_2}}"
      - Network:
          - UniFi:
              icon: unifi.svg
              href: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
              description: network
              widget:
                  type: unifi
                  url: "{{HOMEPAGE_VAR_UNIFI_NETWORK_URL}}"
                  username: "{{HOMEPAGE_VAR_UNIFI_NETWORK_USERNAME}}"
                  password: "{{HOMEPAGE_VAR_UNIFI_NETWORK_PASSWORD}}"
          - Uptime Kuma:
              icon: uptime-kuma.svg
              href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
              description: internal
              widget:
                  type: uptimekuma
                  url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
                  slug: home
          - Uptime Robot:
              icon: https://play-lh.googleusercontent.com/cUrv0t00FYQ1GKLuOTvv8qjo1lSDjqZC16IOp3Fb6ijew6Br5m4o16HhDp0GBu_Bw8Y=w240-h480-rw
              href: https://uptimerobot.com/dashboard
              description: external
              widget:
                  type: uptimerobot
                  url: https://api.uptimerobot.com
                  key: "{{HOMEPAGE_VAR_UPTIME_ROBOT_API_KEY}}"
      - Other:
          - GitLab:
              icon: gitlab.svg
              href: https://gitlab.com
              description: source code
          - GitHub:
              icon: github.svg
              href: https://github.com
              description: source cod
    widgets.yaml: |
      - datetime:
          text_size: xl
          format:
            timeStyle: short

      - kubernetes:
          cluster:
            # Shows cluster-wide statistics
            show: true
            # Shows the aggregate CPU stats
            cpu: true
            # Shows the aggregate memory stats
            memory: true
            # Shows a custom label
            showLabel: true
            label: "cluster"
          nodes:
            # Shows node-specific statistics
            show: true
            # Shows the CPU for each node
            cpu: true
            # Shows the memory for each node
            memory: true
            # Shows the label, which is always the node name
            showLabel: true
    docker.yaml: ""