apiVersion: v1
kind: ConfigMap
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
data:
    kubernetes.yaml: |
      mode: cluster
    settings.yaml: |
      title: YK Homepage
      background:
        image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
        blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
        saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
        brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
        opacity: 100 # 0-100
      theme: dark
      color: slate
      useEqualHeights: true
      layout:
        Core:
          header: true
          style: row
          columns: 4
        Monitoring:
          header: true
          style: row
          columns: 4
        Containers:
          header: true
          style: row
          columns: 4
        Network:
          header: true
          style: row
          columns: 4
        Git:
          header: true
          style: row
          columns: 4
    custom.css: ""
    custom.js: ""
    bookmarks.yaml: ""
    services.yaml: |
      - Core:
          - Proxmox:
              icon: proxmox.svg
              href: "https://10.0.0.2:8006"
              description: node1
          - Pi-Hole-0:
              icon: pi-hole.svg
              href: "https://pihole-0.yuriy-lab.cloud/admin"
              description: pihole-0
          - Pi-Hole-1:
              icon: pi-hole.svg
              href: "https://pihole-1.yuriy-lab.cloud/admin"
              description: pihole-1
          - Longhorn:
              icon: longhorn.svg
              href: "http://10.0.8.102/#/dashboard"
              description: k8s storage
      - Monitoring:
          - Uptime Kuma:
              icon: uptime-kuma.svg
              href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
              description: internal
          - Grafana:
              icon: grafana.svg
              href: "https://grafana.yuriy-lab.cloud"
              description: YK Grafana
          - Alert Manager:
              icon: alertmanager.svg
              href: "https://alertmanager.yuriy-lab.cloud"
              description: YK Grafana
      - Containers:
          - Portainer:
              icon: portainer.svg
              href: "https://portainer.yuriy-lab.cloud"
              description: docker
      - Network:
          - PfSense:
              icon: pfsense.svg
              href: "https://10.0.0.1"
              description: PfSense
      - Git:
          - Gitea:
              icon: gitea.svg
              href: https://gitea.yuriy-lab.cloud
              description: YK Gitea instance
          - ArgoCD:
              icon: argo-cd.svg
              href: https://argocd.yuriy-lab.cloud
              description: YK ArgoCD intance
    widgets.yaml: |
      - datetime:
          text_size: xl
          format:
            timeStyle: short

      - kubernetes:
          cluster:
            # Shows cluster-wide statistics
            show: true
            # Shows the aggregate CPU stats
            cpu: true
            # Shows the aggregate memory stats
            memory: true
            # Shows a custom label
            showLabel: true
            label: "cluster"
          nodes:
            # Shows node-specific statistics
            show: true
            # Shows the CPU for each node
            cpu: true
            # Shows the memory for each node
            memory: true
            # Shows the label, which is always the node name
            showLabel: true
    docker.yaml: ""