replicaCount: 1

image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
  pullPolicy: Always

service:
  port: 3000

homepage:
  allowedHost: homepage.yuriy-lab.cloud

serviceAccount:
  name: homepage