apiVersion: v2
name: kiali-yk
description: Umbrella Helm chart for kiali application in Kubernetes

type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name:  kiali-server
    version: "2.18.0"
    repository: https://kiali.org/helm-charts
    alias: kiali
