yk:
  httpRoutes:

    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: grafana
      hostnames:
        - "kiali.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: kiali
        port: 20001

kiali:
  auth:
    strategy: "anonymous"
  deployment:
    resources:
      requests:
        cpu: "10m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"

  external_services:
    grafana:
      enabled: true
      url: http://grafana-prometheus.monitoring:80
      in_cluster_url: http://grafana-prometheus.monitoring:80
      auth:
        type: bearer
        token: secret:grafana-credentials:token
        use_kiali_token: false
    prometheus:
      url: "http://grafana-prometheus-kube-pr-prometheus.monitoring:9090"

# Hostname for external access via Istio Gateway/VirtualService
kialiGateway:
  host: "kiali.yuriy-lab.cloud"
  login_token:
    signing_key: "token"