apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - vault-reviewer.yaml
patches:
  - path: helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
