apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: vpa
spec:
  interval: 30m
  releaseName: vpa
  chart:
    spec:
      chart: vpa
      version: "5.0.1"
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  timeout: 10m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
