apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  values:
    policyType: ValidatingPolicy
    podSecurityStandard: restricted
    podSecuritySeverity: high
    validationFailureAction: Enforce
    skipBackgroundRequests: true
    vpolExclude:
      excludeNamespaces:
        - kube-system
        - longhorn-system
