apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "healthchecks-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - host
        - remote-node
