apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "ui-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter-ui
  ingress:
    - fromEndpoints:
        - matchLabels:
            gateway.envoyproxy.io/owning-gateway-name: main-gateway
            gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
            io.kubernetes.pod.namespace: envoy-gateway-system
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: policy-reporter
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP
          rules:
            http:
              - {}