apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "kyverno-plugin-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter-kyverno-plugin
  egress:
    - toEntities:
        - host
        - remote-node