apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "kyverno-plugin-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter-kyverno-plugin
  egress:
    - toEntities:
        - host
        - remote-node
    - toFQDNs:
        - matchName: "mirror.gcr.io"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP