apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "trivy-plugin-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: policy-reporter-trivy-plugin
  egress:
    - toFQDNs:
        - matchName: "mirror.gcr.io"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: policy-reporter
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: '8080'
              protocol: TCP
          rules:
            http:
              - {}