apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-pods
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.rbac.serviceAccountName }}
          containers:
            - name: kubectl
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/sh
                - -c
                - |
                  {{- if .Values.cleanup.failed }}
                  echo "Cleaning up Failed pods..."
                  kubectl delete pods --all-namespaces --field-selector=status.phase=Failed --ignore-not-found
                  {{- end }}
                  
                  {{- if .Values.cleanup.succeeded }}
                  echo "Cleaning up Succeeded pods older than {{ .Values.cleanup.succeededMaxAgeSeconds }} seconds..."
                  for ns in $(kubectl get ns --no-headers -o custom-columns=":metadata.name"); do
                    kubectl get pods -n $ns --field-selector=status.phase=Succeeded \
                      -o json | jq -r '.items[] | select(((now - (.status.startTime | fromdateiso8601)) > {{ .Values.cleanup.succeededMaxAgeSeconds }})) | .metadata.name' \
                      | xargs -r -n1 kubectl delete pod -n $ns
                  done
                  {{- end }}
          restartPolicy: OnFailure
