apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace:
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: minio-credentials
  data:
    - secretKey: rootPassword
      remoteRef:
        key: prd/minio
        property: rootPassword
    - secretKey: rootUser
      remoteRef:
        key: prd/minio
        property: rootUser

