apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argo-cd
spec:
  project: infrastructure
  destination:
    namespace: cattle-system
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/rancher/manifest
    helm:
      releaseName: rancher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
