apiVersion: v2
name: traefik-yk
description: Umbrella Helm chart for traefik application in Kubernetes

type: application
version: 37.4.0
appVersion: "37.4.0"

dependencies:
  - name: "traefik"
    version: "37.4.0"
    repository: "https://traefik.github.io/charts"
