apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - helm-release.yaml
  - helm-release-policies.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
