apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: talos-monitoring
  namespace: talos-monitoring
spec:
  interval: 1h
  url: oci://ghcr.io/yuriy-kovalchuk/charts/talos-monitoring
  ref:
    tag: "0.1.0"
