apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authentik-service-ref-grant
  namespace: authentik
spec:
  from:
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: "uptime-kuma"
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: "headlamp"
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: "longhorn-system"
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: "kyverno-reporter"
  to:
    - group: ''
      kind: Service
      name: ak-outpost-proxy