apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "whoami-network-policy"
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: whoami # Or use {} to allow Gateway to all pods in this NS
  ingress:
    - fromEndpoints:
        - matchLabels:
            # Matches the Envoy proxy pods in your gateway namespace
            gateway.envoyproxy.io/owning-gateway-name: main-gateway
            gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
            io.kubernetes.pod.namespace: envoy-gateway-system
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP