apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: whoami-gateway-istio
  namespace: whoami
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  # Selector defines which Istio ingress gateway pods to use
  selector:
    istio: istio  # Default Istio ingress gateway selector
  
  servers:
    - port:
        number: 80
        name: http-whoami
        protocol: HTTP
      hosts:
        - "whoami.gw.yuriy-lab.cloud"
