# test example -> curl -v https://whoami.yuriy-lab.cloud --resolve whoami.yuriy-lab.cloud:443:192.168.0.XXX
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-tls
  namespace: whoami
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://whoami.yuriy-lab.cloud/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Email, X-Auth-Request-Groups"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request /oauth2/auth;
      error_page 401 = /oauth2/start?rd=$escaped_request_uri;
spec:
  ingressClassName: nginx # This specifies that NGINX should handle the Ingress
  tls:
  - hosts:
    - whoami.yuriy-lab.cloud
    secretName: whoami-lab-tls
  rules:
    - host: whoami.yuriy-lab.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80