apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: whoami-gateway
  namespace: whoami
spec:
  selector:
    istio: istio
  servers:
    - port:
        number: 80
        name: https-whoami
        protocol: HTTP
      hosts:
        - whoami.istio.yuriy-lab.cloud
