apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../clean-pods/overlays/workload-prd
  - ../../httpbin/overlays/workload-prd
  - ../../whoami/overlays/workload-prd
  - ../../yk-portfolio/overlays/workload-prd
  - ../../yk-update-checker/overlays/workload-prd
  - ../../cloudflared/overlays/workload-prd
  # pending review:
  # - ../../homepage/overlays/workload-prd
  # - ../../yk-portfolio/overlays/workload-prd
  # - ../../yk-update-checker/overlays/workload-prd
  # standby — re-enable once monitoring stack (PodMonitor CRD) and authentik are deployed:
  # - ../../cloudnative-pg/overlays/workload-prd
