apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../httpbin/overlays/workload-prd
  - ../../whoami/overlays/workload-prd
  - ../../yk-portfolio/overlays/workload-prd
  - ../../yk-update-checker/overlays/workload-prd
  - ../../homepage/overlays/workload-prd
  - ../../immich/overlays/workload-prd
  - ../../opencloud/overlays/workload-prd
  - ../../../platform/forgejo/overlays/workload-prd
  - ../../../llm/llama-cpp/overlays/workload-prd
  - ../../../llm/open-webui/overlays/workload-prd
