apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: renovate-github-lockdown
  namespace: {{ .Release.Namespace | default "renovate" }}
spec:
  endpointSelector:
    matchLabels:
      app: renovate-daily-helm-scan

  # Default deny ingress
  ingress: []

  # Allow only DNS + GitHub egress
  egress:
    # DNS resolution (kube-dns)
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"

    # HTTPS to GitHub
    - toFQDNs:
        - matchPattern: "*"
        #- matchName: "github.com"
        #- matchPattern: "*.githubusercontent.com"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
