apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: renovate-secret
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/renovate
        property: github_token

