apiVersion: v1
kind: Service
metadata:
  name: truenas
  namespace: truenas
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas
  namespace: truenas
subsets:
  - addresses:
      - ip: 10.0.3.3
    ports:
      - name: http
        port: 80
        protocol: TCP
