apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-dns.yaml
  - allow-health-probes.yaml
  - allow-kube-system.yaml
  - allow-gateway-ingress.yaml
  - allow-gateway-frontend.yaml
  - allow-flux-system.yaml
  - generate-same-namespace.yaml
  - cert-manager.yaml
  - longhorn.yaml
  - kyverno.yaml
  - kyverno-reporter.yaml
  - yk-dns-manager.yaml
