apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-egress-alloy-metrics"
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow Alloy"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
      app.kubernetes.io/name: alloy-metrics
  egress:
    - toEndpoints:
        - matchLabels: {}
      authentication:
        mode: "required"