apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: prd/grafana
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: prd/grafana
        property: admin-password

