apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-generic-oauth-secret
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: auth-generic-oauth-secret
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/grafana
        property: client_id
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/grafana
        property: client_secret

