ingress-nginx:
  controller:
    service:
      loadBalancerIP: "10.0.8.100"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring

    ingressClassResource:
      default: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"