apiVersion: apps/v1
kind: Deployment
metadata:
  name: yk-portfolio
  namespace: yk-portfolio
  labels:
    app: yk-portfolio
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: yk-portfolio
  template:
    metadata:
      labels:
        app: yk-portfolio
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: yk-portfolio
          image: ghcr.io/yuriy-kovalchuk/yk-portfolio:latest
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: nginx-tmp
              mountPath: /var/lib/nginx/tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: nginx-tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
