kubeProxyReplacement: true

k8sServiceHost: localhost
k8sServicePort: 7445

ipam:
  mode: kubernetes

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

gatewayAPI:
  enabled: true

bgpControlPlane:
  enabled: true

l2announcements:
  enabled: false

externalIPs:
  enabled: true

envoy:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - "dns:query;ignoreAAAA;labelsContext=source_namespace,source_app,destination_namespace,destination_app"
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - "httpV2:exemplars=true;labelsContext=source_namespace,source_app,destination_namespace,destination_app,traffic_direction"
      - kafka
      - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity"
      - flows-to-world:any-drop=true
    enableOpenMetrics: true
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Networking

grafana:
  dashboards:
    enabled: true
    annotations:
      k8s-sidecar-target-directory: /tmp/dashboards/Networking

bpf:
  masquerade: true
  tproxy: true

operator:
  replicas: 3
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
