apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-istio-vs
  namespace: httpbin
spec:
  hosts:
    - "httpbin.yuriy-lab.cloud""
  gateways:
    - my-gateway
  http:
    - route:
        - destination:
            host: httpbin-httpbingo.httpbin.svc.cluster.local
            port:
              number: 80
