apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: httpbin-istio-gw
  namespace: httpbin
spec:
  gatewayClassName: istio  # <-- Ties it to the Istio controller
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "httpbin.yuriy-lab.cloud"
      allowedRoutes:
        namespaces:
          from: All
