apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-docker-lib
  namespace: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 20Gi
