apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-manager-provider-credentials
  namespace: yk-dns-manager
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: dns-manager-provider-credentials
  data:
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/yk-dns-manager
        property: OPNSENSE_API_KEY
    - secretKey: OPNSENSE_API_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/yk-dns-manager
        property: OPNSENSE_API_SECRET

