# Images built in the homelab (Forgejo Actions, local builds).
#
# Public, which in Harbor means anonymous *pull* only — push still requires a
# user or robot with push permission on the project. That keeps the cluster from
# needing an imagePullSecret for its own images, at the cost of anything on the
# LAN being able to pull them. Harbor is not internet-exposed (internal DNS to
# 10.0.3.3 behind Traefik; the Cloudflare tunnel only publishes yk-portfolio),
# so the exposure is limited to hosts already inside the network.
#
# Deliberately no force_destroy: unlike the proxy caches, nothing in here can be
# re-pulled from anywhere else.
resource "harbor_project" "homelab" {
  name                   = "homelab"
  public                 = true
  storage_quota          = 15
  vulnerability_scanning = true

  # PHASE 4 — see the note in proxy-caches.tf. Enabling it here first is the
  # safer place to start: this project has the least traffic and you control
  # every image in it.
  # deployment_security = "high"
}

# Credentials for the Forgejo Actions runners to push build output.
#
# Harbor composes the login name as <robot_name_prefix><project>+<name>, so this
# resolves to `robot$homelab+forgejo-runner`. The name itself is unrestricted —
# Harbor validates robot *secrets*, not names — but the generated `$` must be
# single-quoted in a shell:
#   docker login harbor.yuriykovalchuk.dev -u 'robot$homelab+forgejo-runner'
# The `robot$` part is the global `robot_name_prefix` setting and can be changed
# via harbor_config_system if that `$` ever becomes a nuisance.
#
# Note it is a robot, not a user: it appears under Projects -> homelab -> Robot
# Accounts, never under Administration -> Users.
#
# The secret is generated by Harbor; read it with:
#   terragrunt output -raw forgejo_runner_secret
resource "harbor_robot_account" "forgejo_runner" {
  name        = "forgejo-runner"
  description = "Forgejo Actions runners — push and pull within the homelab project"
  level       = "project"

  permissions {
    kind      = "project"
    namespace = harbor_project.homelab.name

    access {
      action   = "push"
      resource = "repository"
    }

    access {
      action   = "pull"
      resource = "repository"
    }
  }
}

# Rescan everything on a schedule so reports do not go stale as new CVEs are
# published against images that were already pulled and scanned.
resource "harbor_interrogation_services" "main" {
  vulnerability_scan_policy = "Daily"
}
