apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: gpu-patch.yaml
    target:
      kind: Deployment
      name: llama-cpp
      namespace: llm
