apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../cilium-policies/overlays/workload-prd
  - ../../gpu-tools/overlays/workload-prd
  - ../../kyverno-config/overlays/workload-prd
  - ../../gateway/overlays/workload-prd
  - ../../cluster-issuer/overlays/workload-prd
  - ../../bgp/overlays/workload-prd
  - ../../hubble/overlays/workload-prd
  - ../../cilium-observability/overlays/workload-prd
  - ../../longhorn/overlays/workload-prd
  - ../../metrics-server/overlays/workload-prd
  - ../../forgejo/overlays/workload-prd
  - ../../flux-system/overlays/workload-prd
  - ../../kyverno-reporter/overlays/workload-prd
  - ../../vpa/overlays/workload-prd
  - ../../yk-dns-manager/overlays/workload-prd
  - ../../trivy/overlays/workload-prd
  - ../../trivy-converter/overlays/workload-prd
