apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default-store
spec:
  provider:
    vault:
      server: "https://10.0.10.15:8200"
      path: "secret"
      version: "v2"
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIFKTCCAxGgAwIBAgIUH4ApmAw3hbxEng1c4uvLzkyzKqkwDQYJKoZIhvcNAQEL
        BQAwJDESMBAGA1UECgwJSGFzaGlDb3JwMQ4wDAYDVQQDDAVWYXVsdDAeFw0yNTA5
        MTUxMTU1MTRaFw0yODA5MTQxMTU1MTRaMCQxEjAQBgNVBAoMCUhhc2hpQ29ycDEO
        MAwGA1UEAwwFVmF1bHQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCl
        N3UHTUApR6IyW8kBmQork5wgxsDrzOFSUXPw8tQAWqeVEkdMS6T18ErKXAhBL0Kw
        ZgX2wcSXZWSJXa/FLHUP9beirN/mNyUnRVZN1I/1ro3nUx0Trxvqb5GURoWl5+vN
        XEurE8uXPa0dbH4432KCvPQmktWk4LGjspfmAiIx8bm/YQ5ZNzxDB8UUuKlILOGC
        A6mZxrQj/tOXs2hqqghlBR82l/KL8m89aCXoSifHc+obYbRowYT7rY8nnzckh8JR
        M7zKhV1QfyaNIj+5inhQ2D/limYr5EZY13pDVeQWJrNw/ZdSTR58mxak34YR3hR2
        BuWSByztfFePsfy8NdFXnQAUHhgYNwO4yKlD2LwjeFBkfjJkWPjl1WR9KyUKDXU0
        cSHq3poWP6IlQxdGujsW+sSKpCWN2bHJ/ARr0Y7+VrhazSV8UTgdKeVsMcE/x6xu
        ufIe2naJhfex6yrMTc1bfaDrH1JMafBljmNRh9LpgkCR8gfxNp4i7T6cI87EVhZN
        ydibs/fHeOYJTo8uqAn4SMkK1IUE++pB57MLfgKKWrI4XUlSbRmuNx9Dh7GVxwIU
        yeT7rVx0xNLqfGjr3bFzrqggcRwekcEewvEbXodnEeM/bPzTjDwhxe0DvSR6xmDK
        7Pl6up6QYdyMf5DTipVrpQtttY/DLx97rtoiboY9wwIDAQABo1MwUTAdBgNVHQ4E
        FgQUNrYCRAcD7YJecpBT49yNMEUjlTEwHwYDVR0jBBgwFoAUNrYCRAcD7YJecpBT
        49yNMEUjlTEwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAYFha
        jmvhVmU4kw7O4TEciSkvbdAkDmtLKhibddy46AYS+YfzPGpGe1hPyLQOmKN4w2tj
        cn/ZMA1JeXPo8IDBsH5h7RkSz92FjCOMGQTVA4Z7cmdv27ntS7gkaBygRFcqo+Nl
        jeieZnDKWcHhTqysrMHpzb7vDq8irJTzyM02UwEukigYN3S80UcjeCeMnSZp82dq
        LfQU4lPX+qFJ5b694UPbcZZt2yllDyW0usQj7IKip+f9Pqs8dj64dAaCQ2vz7H84
        Ie+1x4w/kQIqnFxkrbsT/myHYA0SxUgll8vUIamzez2HKO/D8Lk39h1+U5l/Cqa+
        KNw1sFtoyqPHYVLp9CW67mUiJPfRvNFet5R5kJiB5ePV+2OgF0Plejujue2Kcp7y
        tWicss8w8G93eWxULapA9OMieG0cuSvtGKG+Vn8biRowYOxAjLgVaS8IkAUmYpXQ
        BKR46kyO+ajFLoKUHHkL7r2tvWUMpJ3hxPWiOVnXlVSiEPvaGFb8wsNq1NtFAtuT
        ZzMN6fbKLOlrQYL6peZ6L0N+1XGtYAVCJNrOCLH0yZPw9qb1h48drrD3dSfm3T5o
        3tkJA96iR19qJKr9zVU7GHtyRbjcwcXL6d8W+Ihc00EJ9STOAtLJmY4OrpWpvosb
        TUFKFf8dyc6kOOVoBjJYcE327vfZi85zOqbJG+M=
        -----END CERTIFICATE-----
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"