apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: default-store
spec:
  provider:
    vault:
      server: "https://10.0.10.15:8200"
      path: "secret"
      version: "v2"
      tls:
        insecureSkipVerify: true
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"