---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgBz/PmskoeKOfFtSmjJ+MVhvYYk05NxNqB4lIbFs5evoQ6H6+pC3y5XS7xm9lwu6whjou4fCsVfxKXGu7owKh5P3oidKHnWltY2TB4pYD6VMaORSNkdEuTIF9zNaqkYL546euWwSvTSoyWha40BMCsaiJuRDlrr8UxiPHA3jfTMCIq9+Vb7xoZd9YzbpRYJqyOdODyQDUB0Vjs9vSYf/7wlASdgh+XOIwV5SZTlemno3cGyWzVdPsLC8W+//zHk8cmcNRmpIHbYPRkQO3mk6QsS5Xkylc0SVN+UeYboX8SB5tV6WePOrq42OIJh4gACduX9uTG5Vol+bH5rJwwQuEzL9BbVr6Q9TRQwCW1EQGGd32XoirWNfEte+tEwdZ2uku+veA/3v+D/dfV0N2pdAYod5LpvbLa+84e1ZlNrLfY6zv0jFNJODed5YneaWSPuAN0nWHgC1cHd/TAlNZn9DL79LouTXA7Ysqf7j8wAAVq8bAKO6f/g4NWUpXiXG2eaf/kxpw87iH406wHu1yLkEnRtIa5hFSXwb/8seXNywPddksB60bEg1mxarkkd+AZf1kwGEBawnb2mwJQ8AEpAXAQXlMfGZ/qjBMIpO04Pq+Mg2EVDDKFTG8mVJ7Z7pMCHmFAqVF7J17/i4K4CaVlDjc0vdw5beMOmLKOnUzlvy2unWp/K0SJXOPE+uH5xtB3GBLr9wySZM78qQlV4hWGJKOhVSOiSvSFfjOoGQVL4
  template:
    metadata:
      creationTimestamp: null
      name: vault-token
      namespace: external-secrets
