---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-token
  namespace: external-secrets
spec:
  encryptedData:
    token: AgCFjXCkDNrHQ0FYTBfb8iD2waXJBK/vUvXzejKFSc+Yd1ZuxccfxYjhcvQm8s6xt4yiEDrDDhTz1AQq6Mk7BA7izr+5ZSlSW8eMcDxTAblSF/lHTLQar4WUIqDY7Rqvg5Ji8CFse9UIio1nsqhN2bWTSZsjaum+RXY5Gy7nJFRLfKhwPSb6bd/rAKPP+xJ5l+x9300atT6AWc5/YROc2e3q64Od00SxWRSo9mMs2iYk5d6fsAlpusvwELU+SuPXrHOaSIQCmedSe3kLRAQbAXtYbovAQLyRlDKmwM2NUXxxhMteF7hKWFyaJG0R0r+dxv6eanulj570snlqVgou29eNdajtEuz8pUI+1t8I8UYnaOLJJ2gKVsh+CM4pyj96eVf7j7vj2DtVMOHV14uNvGeuDbjVMJYuqZlE8BAkqFc7vYTImgyef5m+pRw3gczEk0jpwjpHtciPfaex6xw0CvTKTtvwyEqzH28HcVL83O3AmajnQRTQRIu71/DwW02E0up4OV1uX/9DcvQ1JLmJcwaQ7rCqXjml/zLD/3+cIXmCHZzj/XwgUkIsKoGjmhHiUomBkqkCr8SvEU6idZAC3m8Bp8kx1EHXqORbSQ7tsrWk9u/1T/WePwaoEs4tRUcUwGRs9NUa3CiNbuqeW480AiPBb78iF2jrQzlsdU6wS8QVJraSVzuEtLOpkjFjkB2eCrgAi9DJAL7bzHKRN7ZlFTsjPoOIXfelmUi/XDdj
  template:
    metadata:
      creationTimestamp: null
      name: vault-token
      namespace: external-secrets
