apiVersion: v2
name: trivy-yk
description: Umbrella Helm chart for trivy application in Kubernetes

type: application
version: 0.31.0
appVersion: "v0.28.0"

dependencies:
  - name: trivy-operator
    version: "0.31.0"
    repository: https://aquasecurity.github.io/helm-charts/
