trivy-operator:
  operator:
    scanJobTimeout: 1h
    scanJobsConcurrentLimit: 3
    infraAssessmentScannerEnabled: false
  serviceMonitor:
    enabled: true
    namespace: monitoring
  trivy:
    resources:
      requests:
        cpu: 10m
        memory: 100M
        # ephemeralStorage: "2Gi"
      limits:
        cpu: 200m
        memory: 800M
        # ephemeralStorage: "2Gi"
    server:
      # -- resources set trivy-server resource
      resources:
        requests:
          cpu: 20m
          memory: 512Mi
          # ephemeral-storage: "2Gi"
        limits:
          cpu: 200m
          memory: 1Gi
          # ephemeral-storage: "2Gi"
    storageSize: "1Gi"
    slow: false
    timeout: "3h"
  service:
    headless: false
