apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - policy-exception.yaml
  - network-policy.yaml

configMapGenerator:
  - name: grafana-dashboards-kubernetes
    namespace: grafana
    files:
      - dashboards/k8s-api.json
      - dashboards/k8s-coredns.json
      - dashboards/k8s-dashboard.json
      - dashboards/k8s-global.json
      - dashboards/k8s-namespaces.json
      - dashboards/k8s-network-mixin.json
      - dashboards/k8s-nodes.json
      - dashboards/k8s-pods.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Kubernetes

  - name: grafana-dashboards-infrastructure
    namespace: grafana
    files:
      - dashboards/node-exporter.json
      - dashboards/cert-manager.json
      - dashboards/hwmon.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Infrastructure

  - name: grafana-dashboards-security
    namespace: grafana
    files:
      - dashboards/trivy.json
      - dashboards/kyverno.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Security

  - name: grafana-dashboards-networking
    namespace: grafana
    files:
    - dashboards/cloudflared.json
    - dashboards/hubble-http.json
    - dashboards/envoy-overview.json
    - dashboards/envoy-downstream.json
    - dashboards/envoy-clusters.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Networking

  - name: grafana-dashboards-storage
    namespace: grafana
    files:
      - dashboards/longhorn.json
      - dashboards/cloudnative-pg.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Storage
