# Stage 1: Build the Go application
FROM golang:1.23-alpine AS builder

# Install git (needed for Go modules)
RUN apk add --no-cache git

# Set the working directory in the container
WORKDIR /app

# Copy Go module files
COPY src/go.mod src/go.sum ./

# Download dependencies
RUN go mod download

# Copy the entire project
COPY src/ .

# Build the Go application from cmd/ingress-watcher
RUN CGO_ENABLED=0 GOOS=linux go build -o /goapp ./cmd/ingress-watcher

# Stage 2: Create the final image
FROM alpine:latest

# Set author information
LABEL maintainer="Yuriy Kovalchuk <yuriy.kovalchuk@proton.me>"

# Set working directory
WORKDIR /app

# Copy the Go binary from the builder stage
COPY --from=builder /goapp .

# Set entrypoint
CMD ["./goapp"]
