apiVersion: v2
name: whoami-yk
description: Umbrella Helm chart for a simple whoami application k8s
version: 1.0.0
appVersion: "1.0.0"


dependencies:
  - name: oauth2-proxy
    version: "8.3.2"
    repository: https://oauth2-proxy.github.io/manifests