oauth2-proxy:
  config:
    clientID: "ffaf8c5b-273f-4656-81b1-0edaeeede85e"
    clientSecret: "dzh8Q~JqujNRqyPlFN5EQWXsnR3efhLb8EBOZcWg"
    cookieSecret: "ckxhdC9wY2JCd0pvdE8wNDE1NjRHc2JpenR5cjRiSDU="

  sessionStorage:
    type: redis
    redis:
      connectionUrl: "redis://whoami-redis:6379"

  # Add Redis dependency
  redis:
    enabled: true

  extraArgs:
    provider: "entra-id"
    azure-tenant: "f6a43c35-26b3-4260-90e9-6d226459c179"
    oidc-issuer-url: "https://login.microsoftonline.com/f6a43c35-26b3-4260-90e9-6d226459c179/v2.0"
    scope: "openid email profile"
    oidc-groups-claim: "groups"
    set-xauthrequest: "true"
    set-authorization-header: "true"
    whitelist-domain: ".yuriy-lab.cloud"
    pass-user-headers: "true"
    cookie-domain: ".yuriy-lab.cloud"
    cookie-secure: "true"
    session-store-type: redis
    redis-connection-url: redis://whoami-redis:6379
    allowed-group: 4cc0e15c-4414-4aa8-b34e-7b20a29cf575

