apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: kyverno-reporter
spec:
  values:
    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 75Mi
        cpu: 5m
    ui:
      enabled: true
      displayMode: dark
      resources:
        limits:
          memory: 200Mi
          cpu: 100m
        requests:
          memory: 75Mi
          cpu: 5m
      httproute:
        enabled: true
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https-kyverno-reporter
        hostnames:
          - "kyverno-reporter.yuriy-lab.cloud"
    plugin:
      kyverno:
        enabled: true
      trivy:
        enabled: true
