---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-v6-password
  namespace: pihole-v6
spec:
  encryptedData:
    PIHOLE_WEB_PASSWORD: AgA3mbRjF5yB72cXu+zeMcoSoNvHXlErkKuBRR4XLkYly206YkwY2K9NK16Oh59yhmJrlJgqTlPMUNZxZomU1sd++kacc4/P01IV32d/OOw3N9dWKchEo04Kadfyac++D1qCqU7KYF6ndrG3RVLjODoQmZ8V3P5KRtBv23m/448b/yrvSLJfddX43Ex3iObVV4ULflezUgL0fmXKS1oNWOWw62VJc52XbFMdVyn5Fv6BUG4mr9BVnFBsedsEoBnnyhqglvS4KkFz6Ra9sxlCaX8bELRGFp82KWaKljtStwsteL2lGpHGqPPE5+FeeTF6Hp7cWw4xmuX0U0NxI5KMZ1oom8KBTR7zgJ7dG7GDIO9YsyBLGsJYKWnDtgU/HHpjrgBPIobixD5iKNqFmDg7QzOD+U4hVtR0+NkkymVk0kX2vtaQ3vLHa3sHaZ+Kyy21TPhd+JLe09PJRXckK9b0B4wW8y9xDOI7o+M9C29b9qD+ye1DzMqFMke4lw14zNhijZtyYYE7oEbIofTjvHg4ie76aHprYdxy4sssyeVm7OQqzeajgt5zZkK4fkxi0GVkc9W3HU/yXZipP1dBnkerlnntxqVxfxAWWOhZd9m7I74iIcVKd5uJwf3IGEZh4FaGJvH90srD+Favs2ERNlhZzQi9b2nRDdR85ekz3HP7B9idjvLIG4uDrF/Yl7BQUl0IQMT8qvjcV5H77WSSrzGe6Vc=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-v6-password
      namespace: pihole
    type: Opaque
