---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-v6-password
  namespace: pihole-v6
spec:
  encryptedData:
    PIHOLE_WEB_PASSWORD: AgBkOerNgWiat//gDvVGntEZQn1UfjBBITEKvV+xYcBQnrm5XSpbDupgoWaWkMyGtIcOzDXvhsIDo+3Ai4ZUrTkKhznpnYeiljlUqEFF+FPoTzlBrVYqo7vgKrKPOyCBLAyCUhyBaMoJxMklVdo/7eZuJeZdYe1c7WkWwdJN1KjtfxNFwxvCPT0EX067fUxSX57lckv0d9R4ilCKBa16H1KLG3zLraAKc1sA4FL1QAhlk+24HVirrKeVwvEGVVxSsJp8R53YTdyZ2/8aLP18YUvXyTSFv5Kcx/m/C/CZoRSWZo7F4C/uTwwIFDyGP9ZZjB3iqbPbfD9LP7dfg/UkU7NeZufj5oxWXGav7LIoZLJc0F1gw8h2f8jm+4R7GtEulopHDsPF+pDQ/jjmQxMFlbNsrVj93HCG/oOfojefDtRF07cWpEnpwWIiQL3eJjctsEFkUKWcrc+3Jp7IEcBdK9+GvrI06l65THaPw6AV+JQ0TSuYxK1DeqLb5d3kCL6V/x7hPOOre4lfrJV33mBoiSs5LUXaklufWbiYQncnxi5qG2KUURl93Y6M3Q1G0reWs5cBw7fFwbjVSSNcQgZ1G4MoR5jBV6AJpm7FmvHHkxVUpgBilTKlJOf58NAAx+GwCujTkgDka2mUcR6BRir0q1ivQYcppuH7J6I6e0eUFevlwJLSByNFjr0rHliLy130LiwCDqfnrt5UQlH4HeLuMZE=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-v6-password
      namespace: pihole-v6
    type: Opaque
