apiVersion: v1
kind: Service
metadata:
  name: pihole-v6-0-svc
  namespace: pihole-v6
spec:
  selector:
    statefulset.kubernetes.io/pod-name: pihole-v6-0
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: web
      port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "10.0.8.155"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-v6-1-svc
  namespace: pihole-v6
spec:
  selector:
    statefulset.kubernetes.io/pod-name: pihole-v6-1
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: web
      port: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "10.0.8.156"
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-v6-svc
  namespace: pihole-v6
spec:
  selector:
    app: pihole-v6
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "10.0.8.157"

