apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: helm-release-vpa-patch.yaml
    target:
      kind: HelmRelease
      name: vpa
      namespace: vpa
  - path: helm-release-goldilocks-patch.yaml
    target:
      kind: HelmRelease
      name: goldilocks
      namespace: vpa
