apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-nfs-config
  namespace: democratic-csi-nfs
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: truenas-nfs-secret
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/democratic-csi
        property: nfs_config

