replicaCount: 1

namespace: ingress-watcher

serviceAccount:
  name: ingress-exporter-sa

image:
  repository: harbor.yuriy-lab.cloud/library/ingress-hostname-exporter
  tag: "1.0.4"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

env:
  OPNSENSE_URI: "https://10.0.8.254"
  OPNSENSE_SKIP_TLS_VERIFY: "true"

secretName: opnsense-credentials
secretKeys:
  key: OPNSENSE_KEY
  secret: OPNSENSE_SECRET
