apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: loki
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: loki-s3-secret
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/minio
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: prd/minio
        property: S3_SECRET_KEY

