{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "tpl.namespace" . }}
  labels:
    {{- include "tpl.labels" (dict "root" . "extra" .Values.namespace.labels) | nindent 4 }}
  annotations:
    {{- include "tpl.annotations" (dict "root" . "extra" .Values.namespace.annotations) | nindent 4 }}
{{- end }}
