apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argo-cd
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/cilium/manifest
    helm:
      releaseName: cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        # This will enable Goldilocks/VPA for the entire namespace
        goldilocks.fairwinds.com/enabled: "true"
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
        - /spec/template/metadata/annotations
        - /spec/updateStrategy/rollingUpdate/partition
        - /status
        - /metadata/creationTimestamp
        - /spec/volumeClaimTemplates
