apiVersion: v2
name: gitea-yk
description: Umbrella Helm chart for gitea application in Kubernetes

type: application
version: 1.0.0
appVersion: "v11.0.1"

# If your app wraps an upstream chart, uncomment and edit the dependency block below
dependencies:
  - name: gitea
    version: "v11.0.1"
    repository: https://dl.gitea.com/charts/
