apiVersion: v2
name: prometheus-crds-yk
description: Umbrella Helm chart for prometheus-crds application in Kubernetes

type: application
version: 25.0.0
appVersion: "25.0.0"

dependencies:
  - name: prometheus-operator-crds
    version: "25.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
