apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubernetes.yaml: |-
{{ .Files.Get "files/kubernetes.yaml" | indent 4 }}
  settings.yaml: |-
{{ .Files.Get "files/settings.yaml" | indent 4 }}
  custom.css: |-
{{ .Files.Get "files/custom.css" | indent 4 }}
  custom.js: |-
{{ .Files.Get "files/custom.js" | indent 4 }}
  bookmarks.yaml: |-
{{ .Files.Get "files/bookmarks.yaml" | indent 4 }}
  services.yaml: |-
{{ .Files.Get "files/services.yaml" | indent 4 }}
  widgets.yaml: |-
{{ .Files.Get "files/widgets.yaml" | indent 4 }}
  docker.yaml: |-
{{ .Files.Get "files/docker.yaml" | indent 4 }}
