apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "homepage.name" . }}
    helm.sh/chart: {{ include "homepage.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    gethomepage.dev/description: {{ .Values.ingress.annotations.description | quote }}
    gethomepage.dev/enabled: {{ .Values.ingress.annotations.enabled | quote }}
    gethomepage.dev/group: {{ .Values.ingress.annotations.group | quote }}
    gethomepage.dev/icon: {{ .Values.ingress.annotations.icon | quote }}
    gethomepage.dev/name: {{ .Values.ingress.annotations.name | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecret }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "homepage.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
