{
 "title": "hwmon",
 "tags": [
  "linux",
  "hwmon",
  "temperature",
  "fan speed",
  "voltage",
  "amperage",
  "power"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_uname_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\r\nnode_hwmon_temp_celsius{instance=~\"$instance\"} \n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\r\n  or on(instance,chip,sensor) label_replace(node_hwmon_temp_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_temp_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")",
     "legendFormat": "{{chip_name}}/{{label}}"
    },
    {
     "expr": "node_hwmon_temp_crit_alarm_celsius{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n  or label_replace(node_hwmon_temp_crit_alarm_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n    unless on(instance,chip,sensor) node_hwmon_sensor_label",
     "legendFormat": "Critical Alarm {{ chip_name }}/{{ label }}"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n  or label_replace(node_hwmon_temp_crit_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n    unless on(instance,chip,sensor) node_hwmon_sensor_label",
     "legendFormat": "Critical  {{ chip_name }}/{{ label }}"
    },
    {
     "expr": "node_hwmon_temp_crit_hyst_celsius{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n  or label_replace(node_hwmon_temp_crit_hyst_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n    unless on(instance,chip,sensor) node_hwmon_sensor_label",
     "legendFormat": "Critical Hysteresis  {{ chip_name }}/{{ label }}"
    },
    {
     "expr": "node_hwmon_temp_max_celsius{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n  or label_replace(node_hwmon_temp_max_celsius{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n    unless on(instance,chip,sensor) node_hwmon_sensor_label",
     "legendFormat": "Max  {{ chip_name }}/{{ label }}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\nnode_hwmon_in_volts{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\n  or on(instance,chip,sensor) label_replace(node_hwmon_in_volts{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_in_volts{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")",
     "legendFormat": "{{ chip_name }}/{{label}}"
    },
    {}
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\r\nnode_hwmon_fan_rpm{instance=~\"$instance\"} \r\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\r\n  or on(instance,chip,sensor) label_replace(node_hwmon_fan_rpm{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_fan_rpm{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")",
     "legendFormat": "{{ chip_name }}/{{ label }}"
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\nnode_hwmon_curr_amps{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\n  or on(instance,chip,sensor) label_replace(node_hwmon_curr_amps{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_curr_amps{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")",
     "legendFormat": "{{ chip_name }}/{{label}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "# The nicest possible display of a metric...\nnode_hwmon_power_average_watt{instance=~\"$instance\"}\n  * on(instance,chip,sensor) group_left(label) node_hwmon_sensor_label \r\n  * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\n# ...but it may filter out metrics that do not have a label, so as a fallback use the machine sensor name\n  or on(instance,chip,sensor) label_replace(node_hwmon_power_average_watt{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\") \r\n    * on(instance,chip) group_left(chip_name) node_hwmon_chip_names\r\n  or on(instance,chip,sensor) label_replace(label_replace(node_hwmon_power_average_watt{instance=~\"$instance\"}, \"label\", \"$0\", \"sensor\", \".*\"), \"chip_name\", \"$0\", \"chip\", \".*\")",
     "legendFormat": "{{ chip_name }}/{{label}}"
    }
   ]
  }
 ]
}