yk:
  ciliumNetworkPolicies:
    - policyName: egress-ext-secret-to-vault
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: external-secrets
      egress:
        - toFQDNs:
            - matchName: "vault.yuriy-lab.cloud"
          toPorts:
            - ports:
                - port: "443"
                  protocol: "TCP"

    - policyName: allow-egress-to-kube-api-server
      endpointSelector: {}
      egress:
        - toEntities:
            - kube-apiserver
            - remote-node
            - host
          toPorts:
            - ports:
                - port: "6443"
                  protocol: TCP
external-secrets:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 256Mi


  serviceMonitor:
    # -- Specifies whether to create a ServiceMonitor resource for collecting Prometheus metrics
    enabled: true
