apiVersion: v2
name: sealed-secrets-yk
description: Umbrella Helm chart for sealed-secrets k8s

type: application
version: 1.0.0
appVersion: "2.17.2"

dependencies:
  - name: sealed-secrets
    version: "2.17.2"
    repository: https://bitnami-labs.github.io/sealed-secrets/
