sealed-secrets:

  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

  podSecurityContext:
    enabled: true
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 10011
    runAsGroup: 10011
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10011
    capabilities:
      drop:
        - ALL
  metrics:
    serviceMonitor:
      enabled: true