apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/yuriy/Homelab
    targetRevision: HEAD
    path: kubernetes/apps/trivy/manifest
    helm:
      releaseName: trivy
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
