vpa:
  recommender:
    extraArgs:
      v: "4"
      pod-recommendation-min-cpu-millicores: 15
      pod-recommendation-min-memory-mb: 32

goldilocks:
  dashboard:
    httpRoute:
      enabled: true
      parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      hostnames:
        - goldilocks.yuriy-lab.cloud
