apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../loki/overlays/workload-prd
  - ../../mimir/overlays/workload-prd
  - ../../tempo/overlays/workload-prd
  - ../../k8s-monitoring/overlays/workload-prd
  - ../../grafana/overlays/workload-prd
