apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  namespace: cdi
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    filesystemOverhead:
      global: "0.055"
  imagePullPolicy: IfNotPresent
