apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-same-namespace-and-dns"
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow communication within the same namespace and to kube-dns."
  endpointSelector: {} # Targets all pods in this namespace
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": {{ .Release.Namespace }}
    - fromEntities:
        - host          # Traffic from the local node (where the pod is running)
        - remote-node   # Traffic from other nodes in the cluster
  egress:
    # Rule 1: Allow egress to pods in the same namespace
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": {{ .Release.Namespace }}
    # Rule 2: Allow egress to DNS in kube-system
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"