apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-grafana-queries"
  namespace: {{ .Release.Namespace }}
spec:
  description: "Allow Grafana queries"
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: mimir
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: grafana
            app.kubernetes.io/instance: grafana
            io.kubernetes.pod.namespace: grafana
      authentication:
        mode: "required"
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP