networkpolicies:
  enabled: false

longhornui:
  replicas: 1

httproute:
  enabled: true
  parentRefs:
    - name: internal
      namespace: kube-system
      group: gateway.networking.k8s.io
      kind: Gateway
      sectionName: https-longhorn
  
