apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - bgp/

patches:
  - path: cert-manager/helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
