apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: mimir-credentials
  data:
    - secretKey: access_key_id
      remoteRef:
        key: prd/mimir
        property: access_key_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret_access_key
      remoteRef:
        key: prd/mimir
        property: secret_access_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

