{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "tpl.fullname" .) .Values.serviceAccount.name }}
  namespace: {{ include "tpl.namespace" . }}
  labels:
    {{- include "tpl.labels" (dict "root" . "extra" (dict)) | nindent 4 }}
  annotations:
    {{- include "tpl.annotations" (dict "root" . "extra" .Values.serviceAccount.annotations) | nindent 4 }}
automountServiceAccountToken: {{ default false .Values.serviceAccount.automount }}
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml .Values.serviceAccount.imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
