{{- $ns := include "tpl.namespace" . -}}
{{- range $i, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-%s" (include "tpl.fullname" $) (default (printf "svc-%d" $i) $svc.name)) $svc.name }}
  namespace: {{ $ns }}
  labels:
    {{- include "tpl.labels" (dict "root" $ "extra" $svc.labels) | nindent 4 }}
  annotations:
    {{- include "tpl.annotations" (dict "root" $ "extra" $svc.annotations) | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $svc.type }}
  selector:
    {{- include "tpl.selectorLabels" (dict "root" $ "name" (default (include "tpl.fullname" $) $svc.selectorName)) | nindent 4 }}
  {{- $defaultPorts := (list (dict "name" "http" "port" 80 "targetPort" 80 "protocol" "TCP")) -}}
  {{- $ports := default $defaultPorts $svc.ports -}}
  ports:
    {{- toYaml $ports | nindent 4 }}
{{- end }}
