yk:
  ciliumNetworkPolicies:
    - policyName: allow-egress-to-kube-api-server
      endpointSelector: {}
      egress:
        - toEntities:
            - kube-apiserver
            - remote-node
            - host
          toPorts:
            - ports:
                - port: "6443"
                  protocol: TCP

    - policyName: allow-egress-to-world
      endpointSelector: {}
      egress:
        - toCIDR:
            - "0.0.0.0/0"

    - policyname: egress-to-oidc
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: dex-server
      egress:
        - toEndpoints:
            - matchLabels:
                gateway.envoyproxy.io/owning-gateway-name: main-gateway
                io.kubernetes.pod.namespace: envoy-gateway-system
          authentication:
            mode: "required"

argo-cd:
  global:
    domain: argocd.yuriy-lab.cloud

  redis-ha:
    enabled: false

  controller:
    replicas: 1

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    metrics:
      enabled: true

  redis:
    metrics:
      enabled: true

  server:
    replicas: 2
    metrics:
      enabled: true

  repoServer:
    replicas: 2
    metrics:
      enabled: true

  applicationSet:
    replicas: 2
    metrics:
      enabled: true


  # TODO Add authentik integrtation
  configs:
    params:
      server.insecure: true
    rbac:
      policy.csv: |
        g, ArgoCD Admins, role:admin
        g, ArgoCD Viewers, role:readonly

  extraObjects:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: argo-route
        namespace: argo-cd
      spec:
        hostnames:
          - argocd.yuriy-lab.cloud
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: main-gateway
            namespace: envoy-gateway-system
        rules:
          - backendRefs:
              - group: ''
                kind: Service
                name: argo-cd-argocd-server
                port: 80
                weight: 1
            matches:
              - path:
                  type: PathPrefix
                  value: /






