yk:
  ciliumNetworkPolicies:
    - policyName: egress-compactor-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: compactor
          app.kubernetes.io/instance: mimir
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"
    - policyName: egress-ingester-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: ingester
          app.kubernetes.io/instance: mimir
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"
    - policyName: egress-querier-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: querier
          app.kubernetes.io/instance: mimir
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"
    - policyName: egress-store-gateway-to-minio
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: store-gateway
          app.kubernetes.io/instance: mimir
      egress:
        - toEndpoints:
            - matchLabels:
                app: minio
                io.kubernetes.pod.namespace: minio
          authentication:
            mode: "required"
    - policyName: ingress-query-frontend-from-grafana
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/component: query-frontend
          app.kubernetes.io/instance: mimir
      ingress:
        - fromEndpoints:
          - matchLabels:
                app.kubernetes.io/name: grafana
                app.kubernetes.io/instance: grafana
                io.kubernetes.pod.namespace: grafana
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "8080"
                  protocol: TCP








mimir-distributed:

  global:
   extraEnvFrom:
     - secretRef:
         name: mimir-credentials

  mimir:
    structuredConfig:
      memberlist:
        cluster_label: "mimir"
        cluster_label_verification_disabled: false

      server:
        log_level: info
        grpc_server_max_recv_msg_size: 104857600
        grpc_server_max_send_msg_size: 104857600
        grpc_server_max_concurrent_streams: 1000

      limits:
        max_label_names_per_series: 120
        max_global_series_per_user: 12000000
        max_global_series_per_metric: 200000000
        compactor_blocks_retention_period: 3d
        max_query_parallelism: 240
        max_queriers_per_tenant: 0

        query_sharding_total_shards: 128
        query_sharding_max_sharded_queries: 256

        request_rate: 0
        request_burst_size: 0

        ingestion_rate: 100000
        ingestion_burst_size: 200000

      query_scheduler:
        max_outstanding_requests_per_tenant: 10000

      blocks_storage:
        backend: s3
        s3:
          endpoint: "minio.minio:9000"
          region: "eu-south-1"
          access_key_id: "${access_key_id}"
          secret_access_key: "${secret_access_key}"
          bucket_name: "mimir-data"
          insecure: true
          http:
            insecure_skip_verify: true

        tsdb:
          dir: /data/tsdb
          block_ranges_period: [ 2h ]
          retention_period: 10h
          ship_interval: 1m
          flush_blocks_on_shutdown: true
          head_compaction_interval: 1m
          wal_compression_enabled: true

      compactor:
        compaction_interval: 2h
        data_dir: /data/compactor


      ingest_storage:
        enabled: false  # Explicitly turn off the Kafka logic

      ingester:
        push_grpc_method_enabled: true # Re-enables direct GRPC ingestion
        ring:
          zone_awareness_enabled: false
          replication_factor: 3
          kvstore:
            store: memberlist

      store_gateway:
        sharding_ring:
          zone_awareness_enabled: false
          replication_factor: 3
          kvstore:
            store: memberlist


  # Receives data from alloy, corrects, devides data to batches and send to ingesters
  distributor:
    replicas: 3
    extraArgs:
      auth.multitenancy-enabled: false
      log.level: info

  # Writes incoming series to long-term storage on the write path and returns series samples for queries on the read path.
  ingester:
    zoneAwareReplication:
      enabled: false
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: "truenas-iscsi"
    replicas: 3

  # Evaluates PromQL expressions by fetching time series and labels on the read path. Uses store-gateway fron minio and ingester for latest data
  querier:
    replicas: 2

  # "frontend" for querier
  query_frontend:
    replicas: 2

  query_scheduler:
    replicas: 2


  # comunication with minio
  store_gateway:
    persistentVolume:
      enabled: true
      size: 2Gi
      storageClass: "truenas-iscsi"
    zoneAwareReplication:
      enabled: false
    replicas: 3

  # Increases query performance and reduces long-term storage usage by combining blocks.
  compactor:
    replicas: 1
    persistentVolume:
      enabled: true
      size: 50Gi
      storageClass: "truenas-iscsi"

  kafka:
    enabled: false


  ## Disabled services:
  rollout_operator:
    enabled: false
  gateway:
    enabledNonEnterprise: false
  ruler:
    enabled: false
  overrides_exporter:
    enabled: false
  alertmanager:
    enabled: false
  minio:
    enabled: false

  metaMonitoring:
    dashboards:
      enabled: true
      namespace: grafana
      labels:
        grafana_dashboard: "1"

    serviceMonitor:
      enabled: true
