apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-envoy-stats
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  podMetricsEndpoints:
    - targetPort: 9090
      path: /metrics
      interval: 30s
      relabelings:
        - replacement: cilium-envoy
          targetLabel: job
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
