apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argo-cd
spec:
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/kiali/manifest
    helm:
      releaseName: kiali
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
      - /metadata/annotations/checksum~1config
      - /spec/template/metadata/annotations/checksum~1config
