apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-manager-provider-credentials
  namespace: yk-dns-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: default-store
    kind: ClusterSecretStore
  target:
    name: dns-manager-provider-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        key: yk-dns-manager/opnsense
        property: OPNSENSE_API_KEY
    - secretKey: OPNSENSE_API_SECRET
      remoteRef:
        key: yk-dns-manager/opnsense
        property: OPNSENSE_API_SECRET
