apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - httproute.yaml
  - policy-exception.yaml
  - storage-class-gpu.yaml
patches:
  - path: helm-release-patch.yaml
    target:
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
