---
- name: Create new VM template from cloud-init image
  async: 600  # Increase wait time (10 minutes)
  poll: 10    # Check status every 10 seconds
  community.general.proxmox_kvm:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    node: "{{ node_target }}"
    name: "{{ template_name }}"
    vmid: 50000
    bios: "seabios"
    boot: 'order=scsi0'
    cores: 1
    sockets: 1
    memory: 4096
    ostype: "{{ image_ostype }}"
    efidisk0:
        storage: "{{ storage_target }}"
        format: raw
        efitype: 4m
        pre_enrolled_keys: 1
    serial:
        serial0: 'socket'
    vga: serial0
    scsihw: 'virtio-scsi-single'
    scsi:
        scsi0: "{{ storage_target }}:0,iothread=1,discard=on,import-from={{ image_dest }}/{{ image_name }},format=raw"
    ide:
        ide2: "{{ storage_target }}:cloudinit,format=raw"
    net:
        net0: 'virtio,bridge=vmbr8'
    template: true