apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-services
  namespace: external-gateway
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: "10.0.4.60"
  listeners:
    - name: https-truenas
      port: 443
      protocol: HTTPS
      hostname: "truenas.yuriykovalchuk.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: truenas-gw-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: "truenas"
    - name: https-s3-console
      port: 443
      protocol: HTTPS
      hostname: "s3.yuriykovalchuk.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: s3-console-gw-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: "s3"
    - name: https-s3-api
      port: 443
      protocol: HTTPS
      hostname: "api.s3.yuriykovalchuk.dev"
      tls:
        mode: Terminate
        certificateRefs:
          - name: s3-api-gw-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: "s3"
