apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: forgejo
  namespace: forgejo
spec:
  matchConditions:
    - name: exclude-forgejo
      expression: "object.metadata.namespace == 'forgejo'"
  policyRefs:
    - kind: ValidatingPolicy
      name: require-run-as-nonroot
    - kind: ValidatingPolicy
      name: require-run-as-non-root-user
    - kind: ValidatingPolicy
      name: disallow-privilege-escalation
    - kind: ValidatingPolicy
      name: restrict-seccomp-strict
