apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argo-cd
spec:
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/parentRefs/0/group
        - /spec/parentRefs/0/kind
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
  project: infrastructure
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/vpa/manifest
    helm:
      releaseName: vpa
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        # This will enable Goldilocks/VPA for the entire namespace
        goldilocks.fairwinds.com/enabled: "true"
