yk:
  ciliumNetwork:
    excludedNamespaces:
      - kube-system
      - argo-cd
      - authentik
      - cert-manager
      - cilium-spire
      - clean-pods
      - cloudnative-pg
      - default
      - dns-sync
      - envoy-gateway-system
      - eraser
      - external-secrets
      - grafana
      - harbor
      - headlamp
      - local-path-storage

  ciliumNetworkPolicies:
    - policyName: same-ns-communication
      type: cluster
      endpointSelector:
        matchExpressions:
          - key: io.kubernetes.pod.namespace
            operator: Exists
      ingress:
        - fromEndpoints:
            - matchExpressions:
                - key: io.kubernetes.pod.namespace
                  operator: Exists
      egress:
        - toEndpoints:
            - matchExpressions:
                - key: io.kubernetes.pod.namespace
                  operator: Exists
        - toEndpoints:
            - matchLabels:
                "k8s:io.kubernetes.pod.namespace": kube-system
                "k8s:k8s-app": kube-dns
          toPorts:
            - ports:
                - port: "53"
                  protocol: ANY
              rules:
                dns:
                  - matchPattern: "*"

    - policyName: envoy-gw-communication
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                gateway.envoyproxy.io/owning-gateway-name: main-gateway
                gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
                io.kubernetes.pod.namespace: envoy-gateway-system
          authentication:
            mode: "required"

    - policyName: alloy-metrics-collection
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
                app.kubernetes.io/name: alloy-metrics
                io.kubernetes.pod.namespace: k8s-monitoring
          authentication:
            mode: "required"

