yk:
  ciliumNetwork:
    excludedNamespaces:
      - kube-system
      - harbor
      - democratic-csi
  ciliumNetworkPolicies:
    - policyName: default-deny-all
      type: cluster
      endpointSelector: {}
      ingress:
        - {}
      egress:
        - {}

    - policyName: envoy-gw-communication
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                gateway.envoyproxy.io/owning-gateway-name: main-gateway
                gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
                io.kubernetes.pod.namespace: envoy-gateway-system
          authentication:
            mode: "required"

    - policyName: alloy-egress-gw-to-k8s
      type: cluster
      endpointSelector:
        matchLabels:
          gateway.envoyproxy.io/owning-gateway-name: main-gateway
          gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
          io.kubernetes.pod.namespace: envoy-gateway-system
      egress:
        - toEndpoints:
            - {}
          authentication:
            mode: "required"

            
    - policyName: alloy-ingress-metrics-collection
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
                app.kubernetes.io/name: alloy-metrics
                io.kubernetes.pod.namespace: k8s-monitoring
          authentication:
            mode: "required"

    - policyName: alloy-egress-metrics-collection
      type: cluster
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
          app.kubernetes.io/name: alloy-metrics
      egress:
        - toEndpoints:
            - {}
          authentication:
            mode: "required"


    - policyName: allow-health-checks
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEntities:
            - host
            - remote-node

    - policyName: allow-egress-cilium-spire-to-nodes
      type: cluster
      endpointSelector:
        matchLabels:
          app: spire-server
      egress:
        - toEntities:
            - host
            - remote-node
            - kube-apiserver
