yk:
  ciliumNetwork:
    excludedNamespaces:
      - kube-system
      - argo-cd
      - authentik
      - cert-manager
      - cilium-spire
      - clean-pods
      - cloudnative-pg
      - default
      - dns-sync
      - envoy-gateway-system
      - eraser
      - external-secrets
      - grafana
      - harbor
      - headlamp
      - local-path-storage

  ciliumNetworkPolicies:
    - policyName: default-deny-all
      type: cluster
      endpointSelector: {}
      ingress:
        - {}
      egress:
        - {}

    - policyName: envoy-gw-communication
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                gateway.envoyproxy.io/owning-gateway-name: main-gateway
                gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
                io.kubernetes.pod.namespace: envoy-gateway-system
          authentication:
            mode: "required"
          toPorts:
            - ports:
                - port: "0"   # matches any port
                  protocol: TCP
              rules:
                http:
                  - {}

    - policyName: alloy-metrics-collection
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEndpoints:
            - matchLabels:
                app.kubernetes.io/instance: k8s-monitoring-alloy-metrics
                app.kubernetes.io/name: alloy-metrics
                io.kubernetes.pod.namespace: k8s-monitoring
          authentication:
            mode: "required"

    - policyName: allow-health-checks
      type: cluster
      endpointSelector:
        {}
      ingress:
        - fromEntities:
            - host
            - remote-node

