# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "terraform-prd"
    endpoint                    = "http://10.0.3.4:9000"
    key                         = "proxmox-nodes/storage/docker-vm.tfstate"
    region                      = "eu-south-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    use_path_style              = true
  }
}
