apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yk-dns-manager
  namespace: yk-dns-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: yk-dns-manager
      sourceRef:
        kind: OCIRepository
        name: yk-dns-manager
        namespace: yk-dns-manager
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: yk-dns-manager-values
      valuesKey: values.yaml
