apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: yk-dns-manager
  namespace: yk-dns-manager
spec:
  interval: 1h
  url: oci://ghcr.io/yuriy-kovalchuk/yk-dns-manager-chart/yk-dns-manager
  ref:
    tag: "0.6.1"
