authentik:

#  first login at https://<ingress-host-name>/if/flow/initial-setup/

  authentik:
    secret_key: file:///postgres-creds/password
    error_reporting:
      enabled: false
    postgresql:
      host: pg-cluster-authentik-rw
      user: file:///postgres-creds/username
      password: file:///postgres-creds/password

  server:
    volumes:
      - name: postgres-creds
        secret:
          secretName: cluster-authentik-user
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      tls:
        - hosts:
            - authentik.yuriy-lab.cloud
          secretName: authentik-ingress-tls
      hosts:
        - authentik.yuriy-lab.cloud
      paths:
        - "/"
      extraPaths:
        - path: /outpost.goauthentik.io/
          pathType: Prefix
          backend:
            service:
              name: ak-outpost-authentik-embedded-outpost
              port:
                number: 9000


  worker:
    volumes:
      - name: postgres-creds
        secret:
          secretName: cluster-authentik-user
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true

  redis:
    enabled: true