yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: outpost
      hostnames:
        - "authentik.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /outpost.goauthentik.io
      backend:
        name: ak-outpost-proxy
        port: 9000

    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: grafana
      hostnames:
        - "authentik.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: authentik-server
        port: 80

  ciliumNetworkPolicies:

    - policyName: allow-ingress-to-authentik-db
      endpointSelector:
        matchLabels:
          cnpg.io/cluster: pg-cluster-authentik
      ingress:
        - fromEndpoints:
          - matchLabels:
              io.kubernetes.pod.namespace: cloudnative-pg
              app.kubernetes.io/name: cloudnative-pg
          toPorts:
            - ports:
                - port: "8000"
                  protocol: TCP

authentik:

#  first login at https://<ingress-host-name>/if/flow/initial-setup/

  authentik:
    secret_key: file:///postgres-creds/password
    error_reporting:
      enabled: false
    postgresql:
      host: pg-cluster-authentik-rw
      user: file:///postgres-creds/username
      password: file:///postgres-creds/password


  server:
    volumes:
      - name: postgres-creds
        secret:
          secretName: cluster-authentik-user
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true


  worker:
    volumes:
      - name: postgres-creds
        secret:
          secretName: cluster-authentik-user
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true

  redis:
    enabled: true
