apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - models-preset-configmap.yaml
  - model-download-job.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: llama-cpp-model-list
    namespace: llm
    files:
      - models.txt
generatorOptions:
  disableNameSuffixHash: true
