apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-models
  namespace: llm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
