apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: inject-cilium-namespace-only-policy
spec:
  generateExisting: true
  background: true
  rules:
    - name: generate-allow-same-namespace-with-hardened-dns
      skipBackgroundRequests: true
      match:
        resources:
          kinds:
            - Namespace
      generate:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        name: allow-same-namespace
        namespace: "{{`{{request.object.metadata.name}}`}}"
        synchronize: true
        data:
          spec:
            endpointSelector: {}
            ingress:
              - fromEndpoints:
                  - {}
            egress:
              - toEndpoints:
                  - {}
              - toEndpoints:
                  - matchLabels:
                      "k8s:io.kubernetes.pod.namespace": kube-system
                      "k8s-app": kube-dns
                toPorts:
                  - ports:
                      - port: "53"
                        protocol: ANY
                    rules:
                      dns:
                        - matchPattern: "*"