apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin
  namespace: httpbin
spec:
  values:
    replicaCount: 2
    podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
