apiVersion: v1
kind: Service
metadata:
  name: s3-console
  namespace: s3
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: s3-console
  namespace: s3
subsets:
  - addresses:
      - ip: 10.0.3.4
    ports:
      - name: http
        port: 9001
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: s3-api
  namespace: s3
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: s3-api
  namespace: s3
subsets:
  - addresses:
      - ip: 10.0.3.4
    ports:
      - name: http
        port: 9000
        protocol: TCP
