apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: opencloud
  namespace: opencloud
spec:
  matchConditions:
    - name: exclude-opencloud
      expression: "object.metadata.namespace == 'opencloud'"
  policyRefs:
    - kind: ValidatingPolicy
      name: require-run-as-nonroot
    - kind: ValidatingPolicy
      name: require-run-as-non-root-user
    - kind: ValidatingPolicy
      name: disallow-privilege-escalation
    - kind: ValidatingPolicy
      name: restrict-seccomp-strict
