apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: democratic-csi-iscsi
spec:
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"

    storageClasses:
      - name: truenas-iscsi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []

    controller:
      driver:
        image:
          tag: "v1.9.5@sha256:746bf6b373ae75f5da8b1e412d13c3e8d0e2e1494654268b9dd6fe1f1e55aade"
          pullPolicy: IfNotPresent

    node:
      hostPID: true
      driver:
        image:
          tag: "v1.9.5@sha256:746bf6b373ae75f5da8b1e412d13c3e8d0e2e1494654268b9dd6fe1f1e55aade"
          pullPolicy: IfNotPresent
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ""

    csiProxy:
      enabled: false

    driver:
      existingConfigSecret: truenas-iscsi-secret
      config:
        driver: freenas-api-iscsi
