schedule: "0 * * * *"   # every hour
cleanup:
  failed: true
  succeeded: true
  succeededMaxAgeSeconds: 3600   # 1 hours
image:
  repository: "rancher/kubectl"
  tag: "v1.32.9-amd64"
  pullPolicy: IfNotPresent
rbac:
  serviceAccountName: cleanup-sa
