apiVersion: v2
name: longhorn-yk
description: Umbrella Helm chart for longhorn application in Kubernetes

type: application
version: 1.9.1
appVersion: "1.9.1"

# If your app wraps an upstream chart, uncomment and edit the dependency block below
dependencies:
  - name: longhorn
    version: "1.9.1"
    repository: https://charts.longhorn.io
