longhorn:
  ingress:
    enabled: true
    host: longhorn.yuriy-lab.cloud
    tls: true
    tlsSecret: longhorn-ingress-tls
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
