yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "longhorn.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: longhorn-frontend
      port: 80

      
  ciliumNetworkPolicies:
    - policyName: egress-csi-resizer-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app: csi-resizer
      egress:
        - toEntities:
          - host
          - remote-node

    - policyName: egress-csi-attacher-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app: csi-attacher
      egress:
        - toEntities:
          - host
          - remote-node

    - policyName: egress-csi-provisioner-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app: csi-provisioner
      egress:
        - toEntities:
          - host
          - remote-node

    - policyName: egress-csi-snapshotter-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app: csi-snapshotter
      egress:
        - toEntities:
          - host
          - remote-node
      
    - policyName: egress-longhorn-to-host
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/instance: longhorn
      egress:
        - toEntities:
          - host
          - remote-node
      
longhorn:

  metrics:
    serviceMonitor:
      # -- Setting that allows the creation of a Prometheus ServiceMonitor resource for Longhorn Manager components.
      enabled: true

  extraObjects:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: longhorn-system
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged

