rancher:
  enabled: true

  fleet:
    enabled: false
  postDelete:
    enabled: false
  webhook:
    enabled: false

  hostname: rancher.yuriy-lab.cloud
  bootstrapPassword: "reijfnerikqgbnitrhgoireqgjoitrqbY9."

  replicas: 1  # HA setup for production

  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi

  # Production-specific settings
  ingress:
    enabled: false

  letsEncrypt:
    email: yuriykovalchuk1992@icloud.com
    environment: prod  # Use production Let's Encrypt
    ingress:
      class: nginx