apiVersion: v2
name: kyverno-reporter-yk
description: Umbrella Helm chart for kyverno-reporter application in Kubernetes

type: application
version: 1.0.0
appVersion: "3.5.0"

dependencies:
  - name: policy-reporter
    version: "3.5.0"
    repository: "https://kyverno.github.io/policy-reporter"


