yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "kyverno-reporter.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: policy-reporter-ui
      port: 8080

policy-reporter:
  resources:
     limits:
       memory: 200Mi
       cpu: 100m
     requests:
       memory: 75Mi
       cpu: 5m

  ui:
    enabled: true
    displayMode: dark

    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 75Mi
        cpu: 5m

  plugin:
    kyverno:
      enabled: true
    trivy:
      enabled: true

