yk:
  httpRoute:
    parentRefs:
      - name: main-gateway
        namespace: envoy-gateway-system
    hostnames:
      - "kyverno-reporter.yuriy-lab.cloud"
    path:
      type: PathPrefix
      value: /
    backend:
      name: policy-reporter-ui
      port: 8080


  ciliumNetworkPolicies:
    - policyName: policy-reporter-to-api-server
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/name: policy-reporter
      egress:
        - toEntities:
            - kube-apiserver
          toPorts:
            - ports:
                - port: "6443"
                  protocol: TCP
    
    - policyName: egress-u
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/name: policy-reporter-ui
      egress:
        - toEndpoints:
          - matchLabels:
              app.kubernetes.io/name: policy-reporter
          authentication:
            mode: "required"
          toPorts:
            - ports:
              - port: "8080"
                protocol: "TCP"
              rules:
                http:
                  - {}

    - policyName: egress-reporter-trivy-plugin-to-github
      type: namespaced
      enpointSelector:
        matchLabels:
          app.kubernetes.io/name: policy-reporter-trivy-plugin
      egress:
        - toFQDNs:
            - matchName: "mirror.grc.io"
            - matchName: "api.github.com"
            - matchName: "github.com"
          toPorts:
            - ports:
                - port: "443"
                  protocol: "TCP"
        - toEndpoints:
          - matchLabels:
              app.kubernetes.io/name: policy-reporter
          authentication:
            mode: "required"
          toPorts:
            - ports:
              - port: '8080'
                protocol: TCP
              rules:
                http:
                  - {}


policy-reporter:
  resources:
     limits:
       memory: 200Mi
       cpu: 100m
     requests:
       memory: 75Mi
       cpu: 5m

  ui:
    enabled: true
    displayMode: dark

    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 75Mi
        cpu: 5m

  plugin:
    kyverno:
      enabled: true
    trivy:
      enabled: true

