policy-reporter:
  resources:
     limits:
       memory: 200Mi
       cpu: 100m
     requests:
       memory: 75Mi
       cpu: 5m

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns
    tls:
      - hosts:
          - kyverno-reporter-api.yuriy-lab.cloud
        secretName: kyverno-reporter-api-ingress-tls
    hosts:
      - host: kyverno-reporter-api.yuriy-lab.cloud
        paths:
          - path: '/'
            pathType: Prefix

  ui:
    enabled: true
    displayMode: dark

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
        "nginx.ingress.kubernetes.io/auth-url": "http://ak-outpost-proxy.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
        "nginx.ingress.kubernetes.io/auth-signin": "https://authentik.yuriy-lab.cloud/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri"
        "nginx.ingress.kubernetes.io/auth-response-headers": "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
        "nginx.ingress.kubernetes.io/auth-snippet": "proxy_set_header X-Forwarded-Host $http_host;"
      tls:
        - hosts:
            - kyverno-reporter.yuriy-lab.cloud
          secretName: kyverno-reporter-ingress-tls
      hosts:
        - host: kyverno-reporter.yuriy-lab.cloud
          paths:
            - path: '/'
              pathType: Prefix
    resources:
      limits:
        memory: 200Mi
        cpu: 100m
      requests:
        memory: 75Mi
        cpu: 5m

  plugin:
    kyverno:
      enabled: true
    trivy:
      enabled: true

