apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-unseal-script
  namespace: vault
data:
  unseal.sh: |
    #!/bin/sh
      POD_URL="http://vault-internal:8200"
      curl --request PUT --data '{"key": "'"${UNSEAL_KEY}"'"}' $POD_URL/v1/sys/unseal
