apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.12.1
    helm:
      parameters:
        - name: controller.service.loadBalancerIP
          value: "10.0.8.100"
        - name: controller.ingressClassResource.default
          value: "true"
        - name: controller.ingressClassResource.annotations.cert-manager\.io/cluster-issuer
          value: "letsencrypt-dns"
        - name: controller.ingressClassResource.annotations.test
          value: "owo"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
