harbor:
  expose:
    type: route
    tls:
      enabled: false
      certSource: none
    route:
      parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
          sectionName: https
          kind: Gateway
          group: gateway.networking.k8s.io
      hosts:
        - harbor.yuriy-lab.cloud

  externalURL: https://harbor.yuriy-lab.cloud

  persistence:
    persistentVolumeClaim:
      registry:
        size: 30Gi
      database:
        size: 512Mi
      redis:
        size: 512Mi

    imageChartStorage:
      filesystem:
        rootdirectory: /home/harbor/storage

  ipFamily:
    ipv6:
      enabled: false

#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true


  portal:
   resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  core:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m





