harbor:
  expose:
    tls:
      certSource: secret
      secret:
        secretName: harbor-tls-ingress
    ingress:
      hosts:
        core: harbor.yuriy-lab.cloud
      className: nginx
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt-dns

  externalURL: https://harbor.yuriy-lab.cloud

  persistence:
    persistentVolumeClaim:
      registry:
        size: 30Gi
      database:
        size: 512Mi
      redis:
        size: 512Mi

    imageChartStorage:
      filesystem:
        rootdirectory: /home/harbor/storage

  ipFamily:
    ipv6:
      enabled: false

#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true


  portal:
   resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m

  core:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m





