apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __APP_NAME__
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:yuriy-kovalchuk/Homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/__APP_NAME__/manifest
    helm:
      releaseName: __APP_NAME__
  destination:
    server: https://kubernetes.default.svc
    namespace: __NAMESPACE__
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
