---

- name: "Initialize vm map if not already present"
  set_fact:
      vm_map: {}

- name: "Create VM from an existing template"
  register: vm_result
  loop: "{{ machines }}"
  community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      node: "{{ node_target }}"
      name: "{{ item.name }}"
      clone: "{{ template_name }}"
      storage: "{{ storage_target }}"



- name: "Add VM results to the existing map"
  set_fact:
      vm_map: "{{ vm_map | combine({ item.name: vm_result.results[idx].vmid }) }}"
  loop: "{{ machines }}"
  loop_control:
      index_var: idx
  when: vm_result is defined

- name: "Debug the content of existing_map"
  debug:
      var: vm_map