---
- name: Update VM configuration
  with_items: "{{ machines }}"
  vars:
    ssh_key_path: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub', errors='ignore') | default('', true) }}"
  community.general.proxmox_kvm:
      api_host: "{{ api_host }}"
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      node: "{{ node_target }}"
      vmid: "{{ vm_map[item.name] }}"
      agent: 1
      tags: "{{ item.tags }}"
      cores: "{{ item.cores }}"
      memory: "{{ item.memory }}"
      bios: "seabios"
      ciuser: "{{ item.ci_user }}"
      cipassword: "{{ item.ci_password }}"
      ipconfig:
          ipconfig0: "{{ item.ip_config }}"
      sshkeys: "{{ ssh_key_path }}"
      net:
          net0: "{{ item.vmbr }}"
      update: true