apiVersion: v2
name: monitoring-stack-yk
description: Umbrella chart for monitoring (Prometheus + Grafana)

type: application
version: 79.8.2
appVersion: "79.6.1"


dependencies:
  - name: kube-prometheus-stack
    version: "79.8.2"
    repository: https://prometheus-community.github.io/helm-charts

