kube-prometheus-stack:
  defaultRules:
    rules:
      kubeApiserverBurnrate: false
      kubeApiserverSlos: false
      kubeControllerManager: false
      kubeSchedulerAlerting: false
      nodeExporterAlerting: false
      windows: false

  prometheus-windows-exporter:
    prometheus:
      monitor:
        enabled: false

  alertmanager:
    enabled: true
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        "cert-manager.io/cluster-issuer": "letsencrypt-dns"
      hosts:
        - alertmanager.yuriy-lab.cloud
      paths:
        - /
      tls:
        - secretName: alertmanager-general-tls
          hosts:
            - alertmanager.yuriy-lab.cloud
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi

  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        "cert-manager.io/cluster-issuer": "letsencrypt-dns"
      hosts:
        - grafana.yuriy-lab.cloud
      tls:
        - secretName: grafana-general-tls
          hosts:
            - grafana.yuriy-lab.cloud
    persistence:
      enabled: true
      type: sts
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  kubeControllerManager:
    endpoints:
      - 10.0.8.2
      - 10.0.8.3
      - 10.0.8.4
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  coreDns:
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  kubeDns:
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  kubeEtcd:
    endpoints:
      - 10.0.8.2
      - 10.0.8.3
      - 10.0.8.4
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  kubeScheduler:
    endpoints:
      - 10.0.8.2
      - 10.0.8.3
      - 10.0.8.4
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  kubeProxy:
    enabled: false
    endpoints:
      - 10.0.8.2
      - 10.0.8.3
      - 10.0.8.4
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  nodeExporter:
    operatingSystems:
      aix:
        enabled: false
      darwin:
        enabled: false

  prometheus-node-exporter:
    extraArgs:
      - --collector.hwmon
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
      - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  prometheusOperator:
    admissionWebhooks:
      deployment:
        service:
          ipDualStack:
            ipFamilies: ["IPv4"]
            ipFamilyPolicy: "SingleStack"
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  prometheus:
    thanosService:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"
    servicePerReplica:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        "cert-manager.io/cluster-issuer": "letsencrypt-dns"
      hosts:
        - prometheus.yuriy-lab.cloud
      paths:
        - /
      tls:
        - secretName: prometheus-general-tls
          hosts:
            - prometheus.yuriy-lab.cloud
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  thanosRuler:
    service:
      ipDualStack:
        ipFamilies: ["IPv4"]
        ipFamilyPolicy: "SingleStack"

  extraManifests:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged