kyverno:
  admissionController:
    replicas: 3
    serviceMonitor:
      enabled: true
      namespace: monitoring
  backgroundController:
    replicas: 3
  cleanupController:
    replicas: 3
  reportsController:
    replicas: 3

  features:
    policyExceptions:
      enabled: true

kyverno-policies:
  skipBackgroundRequests: false