yk:
  ciliumNetworkPolicies:
    - policyName: egress-to-host
      endpointSelector: {}
      type: namespaced
      egress:
        - toEntities:
            - host
            - remote-node
          toPorts:
            - ports:
              - port: "6443"
                protocol: TCP

kyverno:
  admissionController:
    replicas: 3
    serviceMonitor:
      enabled: true
  backgroundController:
    replicas: 3
  cleanupController:
    replicas: 3
  reportsController:
    replicas: 3

  features:
    policyExceptions:
      enabled: true
      namespace: "*"

kyverno-policies:
  skipBackgroundRequests: false
