apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-forgejo
  namespace: forgejo
spec:
  instances: 1
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db
      dataChecksums: true
  storage:
    storageClass: truenas-iscsi
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
