apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: k8s-monitoring-node-exporter
  namespace: k8s-monitoring
spec:
  matchConditions:
    - name: exclude-node-exporter
      expression: "object.metadata.namespace == 'k8s-monitoring'"
  policyRefs:
    - kind: ValidatingPolicy
      name: disallow-host-namespaces
    - kind: ValidatingPolicy
      name: disallow-host-path
    - kind: ValidatingPolicy
      name: disallow-host-ports
    - kind: ValidatingPolicy
      name: restrict-volume-types
---
apiVersion: policies.kyverno.io/v1beta1
kind: PolicyException
metadata:
  name: k8s-monitoring-alloy
  namespace: k8s-monitoring
spec:
  matchConditions:
    - name: exclude-alloy
      expression: "object.metadata.namespace == 'k8s-monitoring'"
  policyRefs:
    - kind: ValidatingPolicy
      name: restrict-seccomp-strict
    - kind: ValidatingPolicy
      name: disallow-privilege-escalation
    - kind: ValidatingPolicy
      name: require-run-as-nonroot
    - kind: ValidatingPolicy
      name: require-run-as-non-root-user
    - kind: ValidatingPolicy
      name: disallow-capabilities
    - kind: ValidatingPolicy
      name: disallow-capabilities-strict
