apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system.yaml
  - longhorn-system.yaml
  - trivy.yaml
  - k8s-monitoring.yaml
  - llm.yaml
  - open-webui.yaml
  - forgejo.yaml
