apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: __APP_NAME__
  namespace: __NAMESPACE__
  annotations: {}
  labels:
    app.kubernetes.io/name: __APP_NAME__
    app.kubernetes.io/instance: __APP_NAME__
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | default "__APP_NAME__.example.com" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: __APP_NAME__
                port:
                  number: {{ .Values.service.port }}
  tls: []
