yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: grafana
      hostnames:
        - "grafana.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: grafana
        port: 80

grafana:

  serviceMonitor:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

  admin:
    existingSecret: "grafana-admin"
    userKey: admin-user
    passwordKey: admin-password

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          uid: mimir-metrics
          access: proxy
          url: http://mimir-query-frontend.mimir.svc.cluster.local:8080/prometheus
          isDefault: true
          version: 1
          editable: true
          jsonData:
           httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: "anonymous"

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      node-exporter-full:
        gnetId: 1860
        revision: 42
        datasource: Prometheus
