yk:
  httpRoutes:
    - parentRefs:
        - name: main-gateway
          namespace: envoy-gateway-system
      name: grafana
      hostnames:
        - "grafana.yuriy-lab.cloud"
      path:
        type: PathPrefix
        value: /
      backend:
        name: grafana
        port: 80

  ciliumNetworkPolicies:
    - policyName: egress-to-query-frontend
      type: namespaced
      endpointSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
      egress:
        - toEndpoints:
            - matchLabels:
                app.kubernetes.io/component: query-frontend
                io.kubernetes.pod.namespace: mimir
          authentication:
            mode: "required"

grafana:

  serviceMonitor:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi

  admin:
    existingSecret: "grafana-admin"
    userKey: admin-user
    passwordKey: admin-password

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Mimir
          type: prometheus
          uid: mimir-metrics
          access: proxy
          url: http://mimir-query-frontend.mimir.svc.cluster.local:8080/prometheus
          isDefault: true
          version: 1
          editable: true
          jsonData:
           httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: "anonymous"
        - name: Loki
          type: loki
          uid: loki-datasource
          access: proxy
          url: http://loki-gateway.loki.svc.cluster.local
          isDefault: false
          version: 1
          editable: true
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: "anonymous"


  sidecar:
    dashboards:
      enabled: true

  extraSecretMounts:
    - name: auth-generic-oauth-secret-mount
      secretName: auth-generic-oauth-secret
      defaultMode: 0440
      mountPath: /etc/secrets/auth_generic_oauth
      readOnly: true

  grafana.ini:
    server:
      root_url: "https://grafana.yuriy-lab.cloud"
      domain: "grafana.yuriy-lab.cloud"
    auth:
      signout_redirect_url: "https://authentik.yuriy-lab.cloud/application/o/grafana/end-session/"
      oauth_auto_login: true
    auth.generic_oauth:
      name: authentik
      enabled: true
      client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
      client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
      scopes: "openid profile email"
      auth_url: "https://authentik.yuriy-lab.cloud/application/o/authorize/"
      token_url: "https://authentik.yuriy-lab.cloud/application/o/token/"
      api_url: "https://authentik.yuriy-lab.cloud/application/o/userinfo/"
      # Optionally map user groups to Grafana roles
      role_attribute_path: contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'


