apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../external-secrets-config/overlays/workload-prd
  - ../../../gateway/overlays/workload-prd
  - ../../../cluster-issuer/overlays/workload-prd
  - ../../../bgp/overlays/workload-prd
  - ../../../longhorn/overlays/workload-prd
  - ../../../democratic-csi-nfs/overlays/workload-prd
  - ../../../democratic-csi-iscsi/overlays/workload-prd
  - ../../../cloudnative-pg/overlays/workload-prd
  - ../../../kubevirt/overlays/workload-prd
  - ../../../cdi/overlays/workload-prd
  - ../../../metrics-server/overlays/workload-prd
